export const defaultLang = "en" as const;

/**
 * 站点语言。key = URL 前缀（默认语言 en 无前缀），value = 语言切换器里的自称名
 * （endonym —— 德国用户看到的应该是 "Deutsch" 而不是 "German"）。
 * 新增语言的完整清单见 README 式说明：
 *   1. 这里加 key + 下面 ui 里加整块翻译
 *   2. astro.config.mjs 的 i18n.locales 与 sitemap.i18n.locales
 *   3. utils.ts 的 htmlLang / ogLocale / dateLocale 映射（漏了会静默退回 en）
 *   4. src/pages/<lang>/ 下的页面壳 + src/i18n/useCases.ts 的场景长文案
 */
export const languages = {
  en: "English",
  zh: "中文",
  ja: "日本語",
  ko: "한국어",
  de: "Deutsch",
  ar: "العربية",
  tr: "Türkçe",
} as const;
export type Lang = keyof typeof languages;

// 哪些语言有博客、哪些页面缺某个语言版本，一律由 src/pages 下的实际文件推导，
// 见 ./routes.ts —— 这类清单只要靠手工维护，加语言时就会漏。

export const ui = {
  en: {
    // -- Announcement（顶部公告条）--
    // 留空串 = 整条不渲染。useTranslations 用 ?? 判空，空串不会 fallback 到其他语言。
    // 改文案会自动换掉 localStorage key（服务端按文案算 hash），关闭过的用户会重新看到新公告。
    "announcement.text": "",
    "announcement.dismiss": "Dismiss announcement",

    // -- Nav --
    "nav.useCases": "Use Cases",
    "nav.pricing": "Pricing",
    "nav.blog": "Blog",
    "nav.tryFree": "Try Free",
    "nav.toggleMenu": "Toggle menu",

    // -- Footer --
    "footer.useCases": "Use Cases",
    "footer.pricing": "Pricing",
    "footer.blog": "Blog",
    "footer.app": "App",
    "footer.terms": "Terms of Service",
    "footer.privacy": "Privacy Policy",
    "footer.refund": "Refund Policy",
    "footer.copyright": "© 2026 All rights reserved.",
    "footer.navLabel": "Footer navigation",

    // -- OG --
    "og.siteName": "LDR - Lighting Design Rendering",

    // -- Hero --
    "hero.title": "Transform Daylight Photos into Professional Nightscape Renderings",
    "hero.subtitle": "AI-powered lighting design visualization. Upload a daytime photo, get a professional nightscape rendering in seconds.",
    "hero.cta": "Start Rendering Free",
    "hero.examples": "See Examples",
    "hero.day": "Day",
    "hero.night": "Night",
    "hero.fallback": "See before/after examples below",
    "hero.scrollGallery": "Scroll to gallery",
    "hero.altDay": "Daytime photo of",
    "hero.altNight": "AI nightscape rendering of",

    // -- Features --
    "features.heading": "Why LDR?",
    "features.speed.title": "Day to Night in Seconds",
    "features.speed.desc": "Upload any daytime architectural or landscape photo and get a professional nightscape rendering instantly.",
    "features.ai.title": "AI-Powered Precision",
    "features.ai.desc": "Our AI understands architectural context, material properties, and light physics for realistic results.",
    "features.seg.title": "Semantic Segmentation",
    "features.seg.desc": "Intelligent scene understanding with HQ-SAM technology separates buildings, sky, vegetation automatically.",
    "features.quality.title": "4K Professional Output",
    "features.quality.desc": "Publication-ready renders at up to 4096px resolution. No watermark on Pro plans.",

    // -- How It Works --
    "how.heading": "How It Works",
    "how.step1.title": "Upload",
    "how.step1.desc": "Upload a daytime photo of any building, landscape, or urban scene",
    "how.step2.title": "Describe",
    "how.step2.desc": "Tell the AI your lighting vision, or let it suggest the perfect design",
    "how.step3.title": "Render",
    "how.step3.desc": "Get your professional nightscape rendering in under 60 seconds",

    // -- Showcase --
    "showcase.heading": "See the Results",
    "showcase.empty": "Showcase images coming soon",
    "showcase.emptyDesc": "Professional nightscape renderings generated by LDR AI",

    // -- CTA --
    "cta.heading": "Ready to Transform Your Lighting Designs?",
    "cta.subtitle": "Join designers and architects using AI to visualize nightscape lighting.",
    "cta.button": "Get Started Free",
    "cta.note": "No credit card required • 1 free render daily",

    // -- Pricing --
    "pricing.heading": "Simple, Transparent Pricing",
    "pricing.subtitle": "Pay per project or subscribe for steady flow · Global USD pricing · Cards / Apple Pay / Google Pay · Alipay for one-time packs",
    "pricing.subSection": "Trial & Subscriptions",
    "pricing.subSectionDesc": "From free trial to monthly subscriptions · upgrade anytime",
    "pricing.packSection": "Project Packs",
    "pricing.packSectionDesc": "Buy by project · no subscription · pack credits never expire",
    "pricing.popular": "Most Popular",
    "pricing.disclaimer": "Packs are non-refundable (credits never expire). Subscriptions can be canceled anytime with no current-period refund.",
    // Plan names
    "pricing.free.name": "Free",
    "pricing.mini.name": "Mini",
    "pricing.pro.name": "Pro",
    "pricing.max.name": "Max",
    "pricing.small.name": "Small",
    "pricing.standard.name": "Standard",
    "pricing.large.name": "Large",
    // Periods
    "pricing.period.forever": "forever",
    "pricing.period.oneTime": "one-time",
    "pricing.period.month": "month",
    // 本币参考价：英文站以 USD 为准，不显示换算 —— 留空串即整行不渲染。
    // key 在 en 里存在是为了让 t() 的键类型覆盖它（PricingTable 无条件读取该键）。
    "pricing.free.localPrice": "",
    "pricing.mini.localPrice": "",
    "pricing.pro.localPrice": "",
    "pricing.max.localPrice": "",
    "pricing.small.localPrice": "",
    "pricing.standard.localPrice": "",
    "pricing.large.localPrice": "",
    // Plans
    "pricing.free.tagline": "Try before you buy",
    "pricing.free.f1": "5 credits on signup",
    "pricing.free.f2": "1 free generation per day",
    "pricing.free.f3": "1K resolution with watermark",
    "pricing.free.f4": "All features available (Canvas + Chat)",
    "pricing.free.cta": "Get Started",
    "pricing.mini.tagline": "First paid tier — try commercial quality",
    "pricing.mini.f1": "5 credits (~2-3 4K commercial images)",
    "pricing.mini.f2": "4K resolution, no watermark",
    "pricing.mini.f3": "All features unlocked",
    "pricing.mini.f4": "Credits never expire",
    "pricing.mini.cta": "Buy Mini",
    "pricing.pro.tagline": "Steady flow — 2-3 projects per month",
    "pricing.pro.f1": "120 credits / month (~60 4K images)",
    "pricing.pro.f2": "Batch generation (5 parallel)",
    "pricing.pro.f3": "Priority generation queue",
    "pricing.pro.f4": "4K no watermark · full feature set",
    "pricing.pro.f5": "Cancel anytime, no next-cycle charge",
    "pricing.pro.cta": "Subscribe to Pro",
    "pricing.max.tagline": "Teams — 10+ projects per month",
    "pricing.max.f1": "400 credits / month (~200 4K images)",
    "pricing.max.f2": "Batch + priority queue",
    "pricing.max.f3": "API access",
    "pricing.max.f4": "Priority email support",
    "pricing.max.f5": "Cancel anytime, no next-cycle charge",
    "pricing.max.cta": "Subscribe to Max",
    "pricing.small.tagline": "One small project, 5-10 images",
    "pricing.small.f1": "30 credits (~15 4K images)",
    "pricing.small.f2": "4K no watermark",
    "pricing.small.f3": "Canvas editor + Chat Agent",
    "pricing.small.f4": "Credits never expire",
    "pricing.small.cta": "Buy Small",
    "pricing.standard.tagline": "Fits a 14-image commercial project",
    "pricing.standard.f1": "80 credits (~40 4K images)",
    "pricing.standard.f2": "Canvas iterative refinement",
    "pricing.standard.f3": "All features + Channel diagram",
    "pricing.standard.f4": "Credits never expire",
    "pricing.standard.cta": "Buy Standard",
    "pricing.large.tagline": "Multi-round iteration or 50+ images",
    "pricing.large.f1": "250 credits (~125 4K images)",
    "pricing.large.f2": "Canvas + Chat + Channel diagram",
    "pricing.large.f3": "Priority support response",
    "pricing.large.f4": "Credits never expire",
    "pricing.large.cta": "Buy Large",

    // -- Pricing FAQ --
    "faq.heading": "Frequently Asked Questions",
    "faq.q1": "Can I try LDR for free?",
    "faq.a1": "Yes. Every account gets 5 credits on signup plus 1 free render per day at 1K resolution. No credit card required.",
    "faq.q2": "What’s the difference between a Pack and a Subscription?",
    "faq.a2": "Packs (Mini, Small, Standard, Large) are one-time purchases with a fixed bundle of credits that never expire. Use them when you have a specific project in mind. Subscriptions (Pro, Max) renew monthly with fresh credits each cycle — best if you have steady ongoing work. You can mix and match: subscribe and still buy a pack when a big project arrives.",
    "faq.q3": "What resolution are the renders?",
    "faq.a3": "Free plan renders at 1K resolution with a watermark. All paid tiers (Mini, Small, Standard, Large, Pro, Max) render at up to 4K (4096px) with no watermark, suitable for professional presentations and publications.",
    "faq.q4": "Do unused pack credits expire?",
    "faq.a4": "No. Pack credits never expire — they stay in your account until you use them. Subscription credits refresh each billing cycle and do not roll over.",
    "faq.q5": "Can I cancel my subscription?",
    "faq.a5": "Yes, you can cancel anytime from the customer portal. Your subscription remains active until the end of the current billing period and there is no refund for the unused portion of that period.",
    "faq.q6": "Are packs refundable?",
    // a6 分三段是因为中间要插一个指向 /refund 的链接。四种语言的语序不同
    // （中文/日文把链接放在句末前，德文放在 "in unserer …" 之后），
    // 所以拆成 前缀 + 链接文字 + 后缀，而不是在文案里硬编码 <a>。
    "faq.a6": "Packs are non-refundable once purchased. Credits never expire, so they remain available until you use them. New subscribers may be eligible for a 7-day money-back guarantee on their first subscription — see our ",
    "faq.a6.link": "Refund Policy",
    "faq.a6.suffix": " for details.",
    "faq.q7": "What payment methods are supported?",
    "faq.a7": "LDR uses Creem Inc. as the Merchant of Record. Currently available methods include major credit cards, Alipay, Apple Pay, and Google Pay — the exact options may vary by region, and the methods shown on the checkout page are authoritative. Alipay is available for one-time purchases only; subscriptions require a card, Apple Pay, or Google Pay. All prices are in USD; local currency is converted automatically at checkout.",
    "faq.q8": "What image formats are supported?",
    "faq.a8": "We accept JPG, PNG, and WebP images up to 20MB. The AI works best with clear daytime architectural or landscape photos.",

    // -- Blog page --
    "blog.heading": "Blog",
    "blog.subtitle": "Practical guides on lighting design visualization, AI rendering workflows, and nightscape planning.",
    "blog.empty": "No posts published yet. Check back soon.",
    "blog.backToBlog": "← Back to Blog",

    // -- Use Cases index --
    "useCases.heading": "How designers use LDR",
    "useCases.subtitle": "Four disciplines. One shared problem: clients need to see nightscape lighting before any fixture is installed. LDR closes that gap for each of them.",
    "useCases.learnMore": "Learn more →",
    "useCases.arch.title": "Architectural Lighting",
    "useCases.arch.desc": "Visualize facade illumination, entry canopies, and historic preservation lighting before installation. For architects, lighting consultants, and design-build contractors.",
    "useCases.arch.keywords": "Facades · Entrances · Historic preservation",
    "useCases.landscape.title": "Landscape Lighting",
    "useCases.landscape.desc": "Preview garden uplighting, pathway lighting, and water feature illumination. For landscape architects and residential estate designers.",
    "useCases.landscape.keywords": "Gardens · Pathways · Water features",
    "useCases.urban.title": "Urban Night Planning",
    "useCases.urban.desc": "Model city-scale night environments, bridge lighting, and public realm illumination. For urban planners, civic designers, and municipal consultants.",
    "useCases.urban.keywords": "Bridges · Public realm · Civic design",
    "useCases.hospitality.title": "Hospitality Lighting",
    "useCases.hospitality.desc": "Render hotel facades, pool decks, rooftop bars, and boutique restaurant ambiance. For hospitality lighting consultants and brand teams.",
    "useCases.hospitality.keywords": "Hotels · Resorts · Restaurants · Bars",
    "useCases.exploreOther": "Explore Other Use Cases",

    // -- Meta (page titles / descriptions) --
    "meta.home.title": "AI Lighting Design Rendering — Day to Night in Seconds",
    "meta.home.desc": "Transform daytime photos into professional nightscape visualizations with AI. Upload a photo, describe your lighting vision, get publication-ready renders instantly.",
    "meta.pricing.title": "Pricing — LDR Lighting Design Rendering",
    "meta.pricing.desc": "Simple pricing for AI-powered nightscape rendering. Start free with 1 render per day, buy a one-time pack from $9, or subscribe from $99/month for 4K output with no watermark.",
    "meta.blog.title": "Blog — Lighting Design Tips & AI Rendering Guides",
    "meta.blog.desc": "Practical guides, tutorials, and tips on AI-powered lighting design rendering, nightscape visualization, and day-to-night photo transformation.",
    "meta.useCases.title": "Use Cases — AI Lighting Design Rendering",
    "meta.useCases.desc": "Explore how architects, lighting designers, and urban planners use LDR to visualize nightscape renderings across architectural, landscape, urban, and hospitality projects.",
  },

  zh: {
    // -- Announcement（顶部公告条）--
    // 支付宝 2026-07-25 上线（Creem 侧能力）。英文站故意留空：海外用户用不到支付宝。
    "announcement.text": "🎉 支付宝已上线，项目包扫码即付",
    "announcement.dismiss": "关闭公告",

    // -- Nav --
    "nav.useCases": "应用场景",
    "nav.pricing": "价格",
    "nav.blog": "博客",
    "nav.tryFree": "免费试用",
    "nav.toggleMenu": "切换菜单",

    // -- Footer --
    "footer.useCases": "应用场景",
    "footer.pricing": "价格",
    "footer.blog": "博客",
    "footer.app": "应用",
    "footer.terms": "服务条款",
    "footer.privacy": "隐私政策",
    "footer.refund": "退款政策",
    "footer.copyright": "© 2026 版权所有",
    "footer.navLabel": "页脚导航",

    // -- OG --
    "og.siteName": "LDR - 灯光设计渲染",

    // -- Hero --
    "hero.title": "将白天照片转化为专业夜景效果图",
    "hero.subtitle": "AI 灯光设计可视化。上传一张白天照片，几秒内获得专业夜景渲染图。",
    "hero.cta": "免费开始渲染",
    "hero.examples": "查看案例",
    "hero.day": "白天",
    "hero.night": "夜晚",
    "hero.fallback": "在下方查看前后对比案例",
    "hero.scrollGallery": "滚动到案例库",
    "hero.altDay": "白天照片：",
    "hero.altNight": "AI 夜景渲染：",

    // -- Features --
    "features.heading": "为什么选择 LDR？",
    "features.speed.title": "秒级白天转夜景",
    "features.speed.desc": "上传任何建筑或景观的白天照片，即刻获得专业夜景渲染图。",
    "features.ai.title": "AI 精准渲染",
    "features.ai.desc": "AI 理解建筑语境、材料属性和光物理，生成真实感强的渲染结果。",
    "features.seg.title": "语义分割",
    "features.seg.desc": "HQ-SAM 智能场景理解技术，自动分离建筑、天空、植被。",
    "features.quality.title": "4K 专业输出",
    "features.quality.desc": "最高 4096px 分辨率，可直接用于专业演示和出版。Pro 计划无水印。",

    // -- How It Works --
    "how.heading": "使用流程",
    "how.step1.title": "上传",
    "how.step1.desc": "上传任意建筑、景观或城市场景的白天照片",
    "how.step2.title": "描述",
    "how.step2.desc": "告诉 AI 您的灯光设计意图，或让 AI 推荐最佳方案",
    "how.step3.title": "渲染",
    "how.step3.desc": "60 秒内获得专业夜景渲染图",

    // -- Showcase --
    "showcase.heading": "查看效果",
    "showcase.empty": "案例图片即将上线",
    "showcase.emptyDesc": "LDR AI 生成的专业夜景渲染图",

    // -- CTA --
    "cta.heading": "准备好改变您的灯光设计了吗？",
    "cta.subtitle": "加入正在使用 AI 可视化夜景灯光的设计师和建筑师行列。",
    "cta.button": "免费开始",
    "cta.note": "无需信用卡 · 每日 1 次免费渲染",

    // -- Pricing --
    "pricing.heading": "简单透明的价格",
    "pricing.subtitle": "按项目购买或月度订阅 · 全球 USD 定价 · 银行卡 / Apple Pay / Google Pay · 项目包支持支付宝",
    "pricing.subSection": "试用与订阅",
    "pricing.subSectionDesc": "从免费试用到月度订阅 · 随时升级",
    "pricing.packSection": "项目包",
    "pricing.packSectionDesc": "按项目购买 · 无需订阅 · 项目包积分永久有效",
    "pricing.popular": "最受欢迎",
    "pricing.disclaimer": "项目包不可退款（积分永久有效）。订阅可随时取消，当前计费周期不退款。",
    // Plan names
    "pricing.free.name": "免费版",
    "pricing.mini.name": "迷你包",
    "pricing.pro.name": "专业版",
    "pricing.max.name": "旗舰版",
    "pricing.small.name": "小型包",
    "pricing.standard.name": "标准包",
    "pricing.large.name": "大型包",
    // Periods
    "pricing.period.forever": "永久",
    "pricing.period.oneTime": "一次性",
    "pricing.period.month": "月",
    // 本币参考价（USD 结算，此处仅为换算提示；留空则不渲染这一行）
    // 汇率 2026-08-10 取 1 USD ≈ ¥7.2，取整到易读数字。汇率漂移后手工更新即可，
    // 不做实时汇率：营销页静态构建，且"约"字样已表明是参考值。
    "pricing.free.localPrice": "",
    "pricing.mini.localPrice": "≈ ¥65",
    "pricing.pro.localPrice": "≈ ¥720/月",
    "pricing.max.localPrice": "≈ ¥1,800/月",
    "pricing.small.localPrice": "≈ ¥430",
    "pricing.standard.localPrice": "≈ ¥940",
    "pricing.large.localPrice": "≈ ¥2,170",
    // Plans
    "pricing.free.tagline": "先试后买",
    "pricing.free.f1": "注册送 5 积分",
    "pricing.free.f2": "每天 1 次免费生成",
    "pricing.free.f3": "1K 分辨率，带水印",
    "pricing.free.f4": "所有功能可用（画布 + Chat）",
    "pricing.free.cta": "免费开始",
    "pricing.mini.tagline": "入门付费 — 体验商用品质",
    "pricing.mini.f1": "5 积分（级 2-3 张 4K 商用图）",
    "pricing.mini.f2": "4K 分辨率，无水印",
    "pricing.mini.f3": "所有功能解锁",
    "pricing.mini.f4": "积分永久有效，不会过期",
    "pricing.mini.cta": "购买 Mini",
    "pricing.pro.tagline": "稳定产出 — 每月 2-3 个项目",
    "pricing.pro.f1": "每月 120 积分（级 60 张 4K 图）",
    "pricing.pro.f2": "批量生成（5 并发）",
    "pricing.pro.f3": "优先生成队列",
    "pricing.pro.f4": "4K 无水印 · 全功能",
    "pricing.pro.f5": "随时取消，不收下一周期费用",
    "pricing.pro.cta": "订阅 Pro",
    "pricing.max.tagline": "团队 — 每月 10+ 个项目",
    "pricing.max.f1": "每月 400 积分（级 200 张 4K 图）",
    "pricing.max.f2": "批量 + 优先队列",
    "pricing.max.f3": "API 访问",
    "pricing.max.f4": "优先邮件支持",
    "pricing.max.f5": "随时取消，不收下一周期费用",
    "pricing.max.cta": "订阅 Max",
    "pricing.small.tagline": "小项目，5-10 张图",
    "pricing.small.f1": "30 积分（级 15 张 4K 图）",
    "pricing.small.f2": "4K 无水印",
    "pricing.small.f3": "画布编辑器 + Chat Agent",
    "pricing.small.f4": "积分永久有效，不会过期",
    "pricing.small.cta": "购买 Small",
    "pricing.standard.tagline": "适合 14 张图的商业项目",
    "pricing.standard.f1": "80 积分（级 40 张 4K 图）",
    "pricing.standard.f2": "画布迭代精修",
    "pricing.standard.f3": "全功能 + 通道图",
    "pricing.standard.f4": "积分永久有效，不会过期",
    "pricing.standard.cta": "购买 Standard",
    "pricing.large.tagline": "多轮迭代或 50+ 张图",
    "pricing.large.f1": "250 积分（级 125 张 4K 图）",
    "pricing.large.f2": "画布 + Chat + 通道图",
    "pricing.large.f3": "优先支持响应",
    "pricing.large.f4": "积分永久有效，不会过期",
    "pricing.large.cta": "购买 Large",

    // -- Pricing FAQ --
    "faq.heading": "常见问题",
    "faq.q1": "可以免费试用 LDR 吗？",
    "faq.a1": "可以。每个账号注册时获得 5 积分，另外每天 1 次免费 1K 渲染。无需信用卡。",
    "faq.q2": "项目包和订阅有什么区别？",
    "faq.a2": "项目包（Mini、Small、Standard、Large）是一次性购买，包含固定积分，且积分永久有效、不会过期。适合有明确项目需求。订阅（Pro、Max）每月自动续费并刷新积分 — 适合持续性工作。两者可以混合使用。",
    "faq.q3": "渲染分辨率是多少？",
    "faq.a3": "免费版为 1K 分辨率，带水印。所有付费版本最高支持 4K（4096px），无水印，可用于专业演示和出版。",
    "faq.q4": "未使用的项目包积分会过期吗？",
    "faq.a4": "不会。项目包积分永久有效，会一直留在账户里直到用完。订阅积分每个计费周期刷新，不累计。",
    "faq.q5": "可以取消订阅吗？",
    "faq.a5": "可以，随时通过客户门户取消。订阅在当前计费周期结束前仍然有效，剩余部分不退款。",
    "faq.q6": "项目包可以退款吗？",
    "faq.a6": "项目包购买后不可退款。积分永久有效，会一直保留直到用完。新订阅用户可能享有 7 天无理由退款保障 — 详见",
    "faq.a6.link": "退款政策",
    "faq.a6.suffix": "。",
    "faq.q7": "支持哪些支付方式？",
    "faq.a7": "LDR 使用 Creem Inc. 作为责任商户。目前可用方式包括主流信用卡、支付宝、Apple Pay 和 Google Pay —— 具体选项可能因地区而异，以结账页实际显示为准。支付宝仅适用于一次性购买（Mini 与项目包），订阅需使用银行卡、Apple Pay 或 Google Pay。所有价格以美元计价，结账时自动换算本币。",
    "faq.q8": "支持哪些图片格式？",
    "faq.a8": "支持 JPG、PNG 和 WebP，最大 20MB。AI 对清晰的白天建筑或景观照片效果最佳。",

    // -- Blog page --
    "blog.heading": "博客",
    "blog.subtitle": "灯光设计可视化、AI 渲染工作流和夜景规划的实用指南。",
    "blog.empty": "暂无文章。请稍后再来。",
    "blog.backToBlog": "← 返回博客",

    // -- Use Cases index --
    "useCases.heading": "设计师如何使用 LDR",
    "useCases.subtitle": "四个领域，一个共同难题：客户需要在安装灯具之前看到夜景灯光效果。LDR 为每个领域解决这个问题。",
    "useCases.learnMore": "了解更多 →",
    "useCases.arch.title": "建筑照明",
    "useCases.arch.desc": "在安装前可视化幕墙照明、入口雨篷和历史建筑保护灯光。适用于建筑师、灯光顾问和设计施工一体化承包商。",
    "useCases.arch.keywords": "幕墙 · 入口 · 历史建筑保护",
    "useCases.landscape.title": "景观照明",
    "useCases.landscape.desc": "预览花园上照灯、路径照明和水景照明效果。适用于景观建筑师和住宅庄园设计师。",
    "useCases.landscape.keywords": "花园 · 路径 · 水景",
    "useCases.urban.title": "城市夜景规划",
    "useCases.urban.desc": "模拟城市尺度夜景环境、桥梁照明和公共空间照明。适用于城市规划师、市政设计师和市政顾问。",
    "useCases.urban.keywords": "桥梁 · 公共空间 · 市政设计",
    "useCases.hospitality.title": "酒店照明",
    "useCases.hospitality.desc": "渲染酒店外立面、泳池甲板、屋顶酒吧和精品餐厅氛围。适用于酒店灯光顾问和品牌团队。",
    "useCases.hospitality.keywords": "酒店 · 度假村 · 餐厅 · 酒吧",
    "useCases.exploreOther": "探索其他应用场景",

    // -- Meta --
    "meta.home.title": "AI 灯光设计渲染 — 秒级白天转夜景",
    "meta.home.desc": "用 AI 将白天照片转化为专业夜景效果图。上传照片，描述灯光设计意图，即刻获得可发布级渲染图。",
    "meta.pricing.title": "价格 — LDR 灯光设计渲染",
    "meta.pricing.desc": "AI 夜景渲染简单定价。免费每天 1 次渲染，一次性包 $9 起，月度订阅 $99 起，4K 无水印。",
    "meta.blog.title": "博客 — 灯光设计技巧与 AI 渲染指南",
    "meta.blog.desc": "AI 灯光设计渲染、夜景可视化和白天转夜景的实用指南、教程和技巧。",
    "meta.useCases.title": "应用场景 — AI 灯光设计渲染",
    "meta.useCases.desc": "了解建筑师、灯光设计师和城市规划师如何使用 LDR 在建筑、景观、城市和酒店项目中可视化夜景渲染。",
  },

  /**
   * 日本語 —— 日本の照明デザイン市場向け。
   *
   * 用語方針：業界の実務語に寄せる。「夜景パース」「ライトアップ」「照明デザイン」
   * 「配光」「色温度」は日本の照明設計者が実際に検索・使用する語。
   * プラン名（Free / Mini / Pro / Max / Small / Standard / Large）は決済画面および
   * アプリ内表記が英語のため、あえて訳さず英語のまま残す（対応が取れなくなるため）。
   * 文体は「です・ます」体。過度な敬語は避け、B2B の実務トーンに揃える。
   */
  ja: {
    // -- Announcement --
    // 支付宝（Alipay）は日本のユーザーに無関係なので空 = 非表示。
    "announcement.text": "",
    "announcement.dismiss": "お知らせを閉じる",

    // -- Nav --
    "nav.useCases": "活用シーン",
    "nav.pricing": "料金",
    "nav.blog": "ブログ",
    "nav.tryFree": "無料で試す",
    "nav.toggleMenu": "メニューを開閉",

    // -- Footer --
    "footer.useCases": "活用シーン",
    "footer.pricing": "料金",
    "footer.blog": "ブログ",
    "footer.app": "アプリ",
    "footer.terms": "利用規約",
    "footer.privacy": "プライバシーポリシー",
    "footer.refund": "返金ポリシー",
    "footer.copyright": "© 2026 All rights reserved.",
    "footer.navLabel": "フッターナビゲーション",

    // -- OG --
    "og.siteName": "LDR - 照明デザインレンダリング",

    // -- Hero --
    "hero.title": "昼間の写真を、プロ品質の夜景パースへ",
    "hero.subtitle": "AI による照明デザインの可視化。昼間の写真をアップロードするだけで、数秒でプロ品質の夜景レンダリングが手に入ります。",
    "hero.cta": "無料でレンダリングを始める",
    "hero.examples": "事例を見る",
    "hero.day": "昼",
    "hero.night": "夜",
    "hero.fallback": "下のビフォーアフター事例をご覧ください",
    "hero.scrollGallery": "ギャラリーへスクロール",
    "hero.altDay": "昼間の写真：",
    "hero.altNight": "AI 夜景レンダリング：",

    // -- Features --
    "features.heading": "LDR が選ばれる理由",
    "features.speed.title": "昼から夜へ、数秒で",
    "features.speed.desc": "建築・ランドスケープの昼間の写真をアップロードするだけで、プロ品質の夜景パースをすぐに生成します。",
    "features.ai.title": "AI による高精度な描写",
    "features.ai.desc": "建築的な文脈、素材の質感、光の物理を理解した AI が、リアルな仕上がりを実現します。",
    "features.seg.title": "セマンティックセグメンテーション",
    "features.seg.desc": "HQ-SAM による高度なシーン解析が、建物・空・植栽を自動で分離します。",
    "features.quality.title": "4K のプロ仕様出力",
    "features.quality.desc": "最大 4096px、提出資料にそのまま使える解像度。有料プランはウォーターマークなし。",

    // -- How It Works --
    "how.heading": "ご利用の流れ",
    "how.step1.title": "アップロード",
    "how.step1.desc": "建築・ランドスケープ・街並みなど、昼間の写真をアップロード",
    "how.step2.title": "指示する",
    "how.step2.desc": "照明のイメージを AI に伝えるか、AI の提案に任せる",
    "how.step3.title": "レンダリング",
    "how.step3.desc": "60 秒以内にプロ品質の夜景パースが完成",

    // -- Showcase --
    "showcase.heading": "生成事例",
    "showcase.empty": "事例画像は近日公開予定です",
    "showcase.emptyDesc": "LDR AI が生成したプロ品質の夜景レンダリング",

    // -- CTA --
    "cta.heading": "照明デザインの伝え方を変えませんか？",
    "cta.subtitle": "AI で夜景照明を可視化する設計者・建築家の仲間入りを。",
    "cta.button": "無料で始める",
    "cta.note": "クレジットカード不要 · 毎日 1 回無料レンダリング",

    // -- Pricing --
    "pricing.heading": "シンプルで明快な料金",
    "pricing.subtitle": "プロジェクト単位でも、月額でも · 全世界 USD 建て · クレジットカード / Apple Pay / Google Pay",
    "pricing.subSection": "無料トライアルと月額プラン",
    "pricing.subSectionDesc": "無料トライアルから月額プランまで · いつでもアップグレード可能",
    "pricing.packSection": "プロジェクトパック",
    "pricing.packSectionDesc": "プロジェクト単位で購入 · 月額契約なし · パックのクレジットは無期限有効",
    "pricing.popular": "人気 No.1",
    "pricing.disclaimer": "プロジェクトパックは返金対象外です（クレジットは無期限有効）。月額プランはいつでも解約できますが、当期分の返金はありません。表示価格は USD 建てで、地域により消費税等が加算される場合があります。",
    // Plan names（決済画面・アプリ内表記に合わせて英語のまま）
    "pricing.free.name": "Free",
    "pricing.mini.name": "Mini",
    "pricing.pro.name": "Pro",
    "pricing.max.name": "Max",
    "pricing.small.name": "Small",
    "pricing.standard.name": "Standard",
    "pricing.large.name": "Large",
    // Periods
    "pricing.period.forever": "永久",
    "pricing.period.oneTime": "買い切り",
    "pricing.period.month": "月",
    // 円換算の参考価格（2026-08-10 時点で 1 USD ≈ 150 円として概算・端数は丸め）
    "pricing.free.localPrice": "",
    "pricing.mini.localPrice": "約 1,350 円",
    "pricing.pro.localPrice": "約 15,000 円/月",
    "pricing.max.localPrice": "約 37,400 円/月",
    "pricing.small.localPrice": "約 8,900 円",
    "pricing.standard.localPrice": "約 19,400 円",
    "pricing.large.localPrice": "約 44,900 円",
    // Plans
    "pricing.free.tagline": "まずは試してから",
    "pricing.free.f1": "登録時に 5 クレジット付与",
    "pricing.free.f2": "毎日 1 回無料で生成",
    "pricing.free.f3": "1K 解像度・ウォーターマークあり",
    "pricing.free.f4": "全機能を利用可能（キャンバス + チャット）",
    "pricing.free.cta": "無料で始める",
    "pricing.mini.tagline": "はじめての有料プラン — 商用品質を体験",
    "pricing.mini.f1": "5 クレジット（4K 商用画像 約 2〜3 枚）",
    "pricing.mini.f2": "4K 解像度・ウォーターマークなし",
    "pricing.mini.f3": "全機能を開放",
    "pricing.mini.f4": "クレジットは無期限有効",
    "pricing.mini.cta": "Mini を購入",
    "pricing.pro.tagline": "継続案件向け — 月 2〜3 プロジェクト",
    "pricing.pro.f1": "月 120 クレジット（4K 画像 約 60 枚）",
    "pricing.pro.f2": "バッチ生成（5 並列）",
    "pricing.pro.f3": "優先生成キュー",
    "pricing.pro.f4": "4K ウォーターマークなし · 全機能",
    "pricing.pro.f5": "いつでも解約可・次回請求なし",
    "pricing.pro.cta": "Pro を契約",
    "pricing.max.tagline": "チーム向け — 月 10 プロジェクト以上",
    "pricing.max.f1": "月 400 クレジット（4K 画像 約 200 枚）",
    "pricing.max.f2": "バッチ生成 + 優先キュー",
    "pricing.max.f3": "API アクセス",
    "pricing.max.f4": "優先メールサポート",
    "pricing.max.f5": "いつでも解約可・次回請求なし",
    "pricing.max.cta": "Max を契約",
    "pricing.small.tagline": "小規模案件、5〜10 枚",
    "pricing.small.f1": "30 クレジット（4K 画像 約 15 枚）",
    "pricing.small.f2": "4K ウォーターマークなし",
    "pricing.small.f3": "キャンバス編集 + チャットエージェント",
    "pricing.small.f4": "クレジットは無期限有効",
    "pricing.small.cta": "Small を購入",
    "pricing.standard.tagline": "14 枚規模の商用案件に最適",
    "pricing.standard.f1": "80 クレジット（4K 画像 約 40 枚）",
    "pricing.standard.f2": "キャンバスでの反復調整",
    "pricing.standard.f3": "全機能 + チャンネル図",
    "pricing.standard.f4": "クレジットは無期限有効",
    "pricing.standard.cta": "Standard を購入",
    "pricing.large.tagline": "多段階の検討や 50 枚以上に",
    "pricing.large.f1": "250 クレジット（4K 画像 約 125 枚）",
    "pricing.large.f2": "キャンバス + チャット + チャンネル図",
    "pricing.large.f3": "優先サポート対応",
    "pricing.large.f4": "クレジットは無期限有効",
    "pricing.large.cta": "Large を購入",

    // -- Pricing FAQ --
    "faq.heading": "よくあるご質問",
    "faq.q1": "LDR は無料で試せますか？",
    "faq.a1": "はい。アカウント登録時に 5 クレジットを付与し、さらに毎日 1 回、1K 解像度で無料生成できます。クレジットカードの登録は不要です。",
    "faq.q2": "プロジェクトパックと月額プランの違いは？",
    "faq.a2": "プロジェクトパック（Mini・Small・Standard・Large）は買い切りで、決まった数のクレジットが無期限で使えます。具体的な案件が決まっているときに向いています。月額プラン（Pro・Max）は毎月自動更新され、サイクルごとにクレジットが補充されます。継続的に案件がある場合はこちらが有利です。併用も可能で、月額プランを契約したうえで大型案件のときだけパックを追加購入できます。",
    "faq.q3": "レンダリングの解像度は？",
    "faq.a3": "無料プランは 1K 解像度・ウォーターマークありです。有料プラン（Mini・Small・Standard・Large・Pro・Max）はすべて最大 4K（4096px）・ウォーターマークなしで、プレゼン資料や出版物にそのまま使えます。",
    "faq.q4": "使い切らなかったパックのクレジットは失効しますか？",
    "faq.a4": "いいえ。パックのクレジットは無期限有効で、使い切るまでアカウントに残ります。月額プランのクレジットは毎回の請求サイクルでリセットされ、翌月へ繰り越されません。",
    "faq.q5": "月額プランは解約できますか？",
    "faq.a5": "はい、カスタマーポータルからいつでも解約できます。解約後も当期の請求期間が終わるまではご利用いただけますが、残り期間分の返金はありません。",
    "faq.q6": "パックは返金できますか？",
    "faq.a6": "プロジェクトパックはご購入後の返金を承っておりません。クレジットは無期限有効なので、使い切るまで残ります。初回の月額プランについては 7 日間の返金保証の対象となる場合があります。詳しくは",
    "faq.a6.link": "返金ポリシー",
    "faq.a6.suffix": "をご覧ください。",
    "faq.q7": "対応している支払い方法は？",
    "faq.a7": "LDR は Creem Inc. を Merchant of Record（販売事業者）としています。現在ご利用いただける方法は主要クレジットカード、Apple Pay、Google Pay です。地域によって選択肢が異なる場合があり、決済画面に表示される方法が最終的なものとなります。価格はすべて USD 建てで、決済時に自動的に現地通貨へ換算されます。",
    "faq.q8": "対応している画像形式は？",
    "faq.a8": "JPG・PNG・WebP、最大 20MB まで対応しています。輪郭のはっきりした昼間の建築・ランドスケープ写真がもっとも良い結果になります。",

    // -- Blog page（日本語ブログ記事は未整備。langsWithBlog に ja を追加すれば導線が出る）--
    "blog.heading": "ブログ",
    "blog.subtitle": "照明デザインの可視化、AI レンダリングのワークフロー、夜景計画についての実践ガイド。",
    "blog.empty": "記事はまだありません。近日公開予定です。",
    "blog.backToBlog": "← ブログ一覧へ戻る",

    // -- Use Cases index --
    "useCases.heading": "デザイナーは LDR をこう使う",
    "useCases.subtitle": "4 つの領域に共通する課題は一つ — 器具を 1 台も設置する前に、施主は夜の見え方を確認したい。LDR はその隔たりを埋めます。",
    "useCases.learnMore": "詳しく見る →",
    "useCases.arch.title": "建築照明",
    "useCases.arch.desc": "ファサード照明、エントランスキャノピー、歴史的建造物のライトアップを施工前に可視化。建築家・照明コンサルタント・設計施工会社向け。",
    "useCases.arch.keywords": "ファサード · エントランス · 歴史的建造物",
    "useCases.landscape.title": "ランドスケープ照明",
    "useCases.landscape.desc": "庭園のアッパーライト、園路照明、水景照明の効果を事前に確認。ランドスケープアーキテクトや住宅外構デザイナー向け。",
    "useCases.landscape.keywords": "庭園 · 園路 · 水景",
    "useCases.urban.title": "都市夜景計画",
    "useCases.urban.desc": "都市スケールの夜間環境、橋梁ライトアップ、公共空間の照明をシミュレーション。都市計画者・行政デザイナー・自治体コンサルタント向け。",
    "useCases.urban.keywords": "橋梁 · 公共空間 · 都市デザイン",
    "useCases.hospitality.title": "ホスピタリティ照明",
    "useCases.hospitality.desc": "ホテルのファサード、プールデッキ、ルーフトップバー、レストランの雰囲気を再現。ホスピタリティ照明コンサルタントやブランドチーム向け。",
    "useCases.hospitality.keywords": "ホテル · リゾート · レストラン · バー",
    "useCases.exploreOther": "他の活用シーンを見る",

    // -- Meta --
    "meta.home.title": "AI 照明デザインレンダリング — 昼から夜へ数秒で",
    "meta.home.desc": "AI で昼間の写真をプロ品質の夜景パースに。写真をアップロードして照明イメージを伝えるだけで、提案書に使えるレンダリングがすぐ手に入ります。",
    "meta.pricing.title": "料金 — LDR 照明デザインレンダリング",
    "meta.pricing.desc": "AI 夜景レンダリングの明快な料金。毎日 1 回無料、買い切りパックは $9 から、月額プランは $99 から（4K・ウォーターマークなし）。",
    "meta.blog.title": "ブログ — 照明デザインと AI レンダリングのガイド",
    "meta.blog.desc": "AI 照明デザインレンダリング、夜景可視化、昼夜変換についての実践ガイド・チュートリアル・ノウハウ。",
    "meta.useCases.title": "活用シーン — AI 照明デザインレンダリング",
    "meta.useCases.desc": "建築家・照明デザイナー・都市計画者が、建築／ランドスケープ／都市／ホスピタリティの各案件で LDR をどう使っているかをご紹介します。",
  },

  /**
   * 한국어 —— 한국 조명디자인 시장 대상.
   *
   * 용어 원칙: 업계에서 실제로 쓰는 말을 쓴다.
   * - 「경관조명」은 경관법에 근거한 이 분야의 공식 용어이고,
   *   「야간경관 계획」은 서울시 등 지자체가 실제로 발주하는 사업명이다.
   *   urban-night-planning 을 "도시 야경 계획"이 아니라 「야간경관 계획」이라 부르는 이유.
   * - landscape 는 「조경조명」(조경 = landscape architecture), architectural 은 「건축조명」.
   * - 「등기구」(luminaire), 「색온도」, 「업라이팅」, 「투시도/렌더링」은 실무 표기 그대로.
   * 문체는 하십시오체(-습니다). 버튼은 한국 UI 관행대로 「-하기」 명사형.
   * 조사(을/를, 은/는, 이/가)는 앞 글자의 받침에 맞춘다 —— "LDR"은 [엘디알]로 읽어
   * 받침이 있으므로 「LDR을 / LDR은 / LDR이」가 맞다.
   * 플랜 이름(Free / Mini / Pro / Max / Small / Standard / Large)은 앱·결제 페이지
   * 표기가 영문이라 그대로 둔다.
   */
  ko: {
    // -- Announcement --
    // 알리페이는 한국 사용자와 무관하므로 비워 둔다 = 공지 배너 자체가 렌더링되지 않음.
    "announcement.text": "",
    "announcement.dismiss": "공지 닫기",

    // -- Nav --
    "nav.useCases": "활용 사례",
    "nav.pricing": "요금제",
    "nav.blog": "블로그",
    // 독일어에서 겪은 문제와 같은 이유로 짧게: 모바일 헤더에서 줄바꿈되면 안 된다
    "nav.tryFree": "무료 체험",
    "nav.toggleMenu": "메뉴 열기/닫기",

    // -- Footer --
    "footer.useCases": "활용 사례",
    "footer.pricing": "요금제",
    "footer.blog": "블로그",
    "footer.app": "앱",
    "footer.terms": "이용약관",
    "footer.privacy": "개인정보처리방침",
    "footer.refund": "환불 정책",
    "footer.copyright": "© 2026 All rights reserved.",
    "footer.navLabel": "푸터 내비게이션",

    // -- OG --
    "og.siteName": "LDR - 조명디자인 렌더링",

    // -- Hero --
    "hero.title": "낮 사진을 전문가급 야경 렌더링으로",
    "hero.subtitle": "AI 기반 조명디자인 시각화. 낮에 찍은 사진 한 장을 올리면 몇 초 만에 전문가급 야경 렌더링이 완성됩니다.",
    "hero.cta": "무료로 렌더링 시작하기",
    "hero.examples": "사례 보기",
    "hero.day": "낮",
    "hero.night": "밤",
    "hero.fallback": "아래에서 전후 비교 사례를 확인하세요",
    "hero.scrollGallery": "갤러리로 이동",
    "hero.altDay": "낮 사진:",
    "hero.altNight": "AI 야경 렌더링:",

    // -- Features --
    "features.heading": "LDR을 선택하는 이유",
    "features.speed.title": "낮에서 밤까지, 단 몇 초",
    "features.speed.desc": "건축물이나 조경의 낮 사진을 올리기만 하면 전문가급 야경 렌더링이 바로 완성됩니다.",
    "features.ai.title": "AI 기반 정밀 렌더링",
    "features.ai.desc": "건축적 맥락, 재질 특성, 빛의 물리를 이해하는 AI가 사실적인 결과물을 만들어냅니다.",
    "features.seg.title": "시맨틱 세그멘테이션",
    "features.seg.desc": "HQ-SAM 기반 장면 분석이 건물, 하늘, 식재를 자동으로 분리합니다.",
    "features.quality.title": "4K 전문가용 출력",
    "features.quality.desc": "최대 4096px, 발표 자료와 출판물에 바로 쓸 수 있는 해상도. 유료 플랜은 워터마크가 없습니다.",

    // -- How It Works --
    "how.heading": "이용 방법",
    "how.step1.title": "업로드",
    "how.step1.desc": "건축물, 조경, 도시 경관 등 낮에 찍은 사진을 올립니다",
    "how.step2.title": "설명",
    "how.step2.desc": "원하는 조명 콘셉트를 AI에 전달하거나, AI의 제안을 받습니다",
    "how.step3.title": "렌더링",
    "how.step3.desc": "60초 안에 전문가급 야경 렌더링이 완성됩니다",

    // -- Showcase --
    "showcase.heading": "결과물 보기",
    "showcase.empty": "사례 이미지는 곧 공개됩니다",
    "showcase.emptyDesc": "LDR AI로 생성한 전문가급 야경 렌더링",

    // -- CTA --
    "cta.heading": "조명디자인을 보여주는 방식을 바꿔보세요",
    "cta.subtitle": "AI로 야간 조명을 시각화하는 디자이너와 건축가들과 함께하세요.",
    "cta.button": "무료로 시작하기",
    "cta.note": "신용카드 불필요 · 매일 1회 무료 렌더링",

    // -- Pricing --
    "pricing.heading": "간단하고 투명한 요금제",
    "pricing.subtitle": "프로젝트 단위 결제 또는 월 구독 · 전 세계 USD 기준 · 신용카드 / Apple Pay / Google Pay",
    "pricing.subSection": "무료 체험 및 구독 플랜",
    "pricing.subSectionDesc": "무료 체험부터 월 구독까지 · 언제든 변경 가능",
    "pricing.packSection": "프로젝트 패키지",
    "pricing.packSectionDesc": "프로젝트 단위 구매 · 구독 없음 · 패키지 크레딧은 소멸되지 않음",
    "pricing.popular": "가장 인기",
    "pricing.disclaimer": "프로젝트 패키지는 구매 후 환불되지 않습니다(크레딧은 소멸되지 않습니다). 구독은 언제든 해지할 수 있으나 현재 결제 주기에 대한 환불은 없습니다. 표시 가격은 USD 기준이며 지역에 따라 부가세가 추가될 수 있습니다.",
    // Plan names（앱·결제 페이지 표기에 맞춰 영문 유지）
    "pricing.free.name": "Free",
    "pricing.mini.name": "Mini",
    "pricing.pro.name": "Pro",
    "pricing.max.name": "Max",
    "pricing.small.name": "Small",
    "pricing.standard.name": "Standard",
    "pricing.large.name": "Large",
    // Periods
    "pricing.period.forever": "평생",
    "pricing.period.oneTime": "1회 결제",
    "pricing.period.month": "월",
    // 원화 참고가（2026-08-10 기준 1 USD ≈ 1,400원으로 환산 후 반올림）
    "pricing.free.localPrice": "",
    "pricing.mini.localPrice": "약 12,600원",
    "pricing.pro.localPrice": "약 138,000원/월",
    "pricing.max.localPrice": "약 349,000원/월",
    "pricing.small.localPrice": "약 83,000원",
    "pricing.standard.localPrice": "약 181,000원",
    "pricing.large.localPrice": "약 419,000원",
    // Plans
    "pricing.free.tagline": "먼저 써보고 결정하세요",
    "pricing.free.f1": "가입 시 5크레딧 지급",
    "pricing.free.f2": "매일 1회 무료 생성",
    "pricing.free.f3": "1K 해상도, 워터마크 포함",
    "pricing.free.f4": "모든 기능 사용 가능(캔버스 + 챗)",
    "pricing.free.cta": "무료로 시작하기",
    "pricing.mini.tagline": "첫 유료 플랜 — 상업용 품질 체험",
    "pricing.mini.f1": "5크레딧(4K 상업용 이미지 약 2~3장)",
    "pricing.mini.f2": "4K 해상도, 워터마크 없음",
    "pricing.mini.f3": "모든 기능 잠금 해제",
    "pricing.mini.f4": "크레딧 소멸 없음",
    "pricing.mini.cta": "Mini 구매",
    "pricing.pro.tagline": "꾸준한 작업량 — 월 2~3개 프로젝트",
    "pricing.pro.f1": "월 120크레딧(4K 이미지 약 60장)",
    "pricing.pro.f2": "일괄 생성(5개 동시)",
    "pricing.pro.f3": "우선 생성 대기열",
    "pricing.pro.f4": "4K 워터마크 없음 · 전체 기능",
    "pricing.pro.f5": "언제든 해지, 다음 주기 청구 없음",
    "pricing.pro.cta": "Pro 구독",
    "pricing.max.tagline": "팀 단위 — 월 10개 이상 프로젝트",
    "pricing.max.f1": "월 400크레딧(4K 이미지 약 200장)",
    "pricing.max.f2": "일괄 생성 + 우선 대기열",
    "pricing.max.f3": "API 연동",
    "pricing.max.f4": "우선 이메일 지원",
    "pricing.max.f5": "언제든 해지, 다음 주기 청구 없음",
    "pricing.max.cta": "Max 구독",
    "pricing.small.tagline": "소규모 프로젝트, 5~10장",
    "pricing.small.f1": "30크레딧(4K 이미지 약 15장)",
    "pricing.small.f2": "4K 워터마크 없음",
    "pricing.small.f3": "캔버스 편집 + 챗 에이전트",
    "pricing.small.f4": "크레딧 소멸 없음",
    "pricing.small.cta": "Small 구매",
    "pricing.standard.tagline": "14장 규모 상업 프로젝트에 적합",
    "pricing.standard.f1": "80크레딧(4K 이미지 약 40장)",
    "pricing.standard.f2": "캔버스에서 반복 보정",
    "pricing.standard.f3": "전체 기능 + 채널 다이어그램",
    "pricing.standard.f4": "크레딧 소멸 없음",
    "pricing.standard.cta": "Standard 구매",
    "pricing.large.tagline": "여러 차례 수정 또는 50장 이상",
    "pricing.large.f1": "250크레딧(4K 이미지 약 125장)",
    "pricing.large.f2": "캔버스 + 챗 + 채널 다이어그램",
    "pricing.large.f3": "우선 지원 응대",
    "pricing.large.f4": "크레딧 소멸 없음",
    "pricing.large.cta": "Large 구매",

    // -- Pricing FAQ --
    "faq.heading": "자주 묻는 질문",
    "faq.q1": "LDR을 무료로 사용해볼 수 있나요?",
    "faq.a1": "네. 가입하면 5크레딧이 지급되고, 매일 1회 1K 해상도로 무료 생성할 수 있습니다. 신용카드 등록은 필요하지 않습니다.",
    "faq.q2": "프로젝트 패키지와 구독은 어떻게 다른가요?",
    "faq.a2": "프로젝트 패키지(Mini, Small, Standard, Large)는 1회 결제로 정해진 크레딧을 받는 방식이며 크레딧은 소멸되지 않습니다. 진행할 프로젝트가 정해져 있을 때 적합합니다. 구독(Pro, Max)은 매월 갱신되며 주기마다 크레딧이 새로 지급되므로, 작업이 꾸준히 있을 때 유리합니다. 두 가지를 함께 쓸 수도 있어 구독 중에 큰 프로젝트가 생기면 패키지를 추가로 구매하면 됩니다.",
    "faq.q3": "렌더링 해상도는 어떻게 되나요?",
    "faq.a3": "무료 플랜은 1K 해상도에 워터마크가 포함됩니다. 유료 플랜(Mini, Small, Standard, Large, Pro, Max)은 모두 최대 4K(4096px), 워터마크 없이 출력되어 발표 자료나 출판물에 바로 사용할 수 있습니다.",
    "faq.q4": "사용하지 않은 패키지 크레딧은 소멸되나요?",
    "faq.a4": "아니요. 패키지 크레딧은 소멸되지 않으며 다 쓸 때까지 계정에 남아 있습니다. 구독 크레딧은 결제 주기마다 초기화되며 다음 달로 이월되지 않습니다.",
    "faq.q5": "구독을 해지할 수 있나요?",
    "faq.a5": "네, 고객 포털에서 언제든 해지할 수 있습니다. 해지 후에도 현재 결제 주기가 끝날 때까지는 이용할 수 있으며 남은 기간에 대한 환불은 없습니다.",
    "faq.q6": "패키지는 환불되나요?",
    "faq.a6": "프로젝트 패키지는 구매 후 환불되지 않습니다. 크레딧은 소멸되지 않으므로 다 쓸 때까지 그대로 남아 있습니다. 첫 구독에 한해 7일 환불 보장이 적용될 수 있습니다. 자세한 내용은 ",
    "faq.a6.link": "환불 정책",
    "faq.a6.suffix": "을 확인해 주세요.",
    "faq.q7": "어떤 결제 수단을 지원하나요?",
    "faq.a7": "LDR의 판매 사업자(Merchant of Record)는 Creem Inc.입니다. 현재 주요 신용카드, Apple Pay, Google Pay를 지원하며 이용 가능한 수단은 지역에 따라 다를 수 있습니다. 결제 페이지에 표시되는 수단이 기준입니다. 모든 가격은 USD 기준이며 결제 시 자동으로 현지 통화로 환산됩니다.",
    "faq.q8": "어떤 이미지 형식을 지원하나요?",
    "faq.a8": "JPG, PNG, WebP를 최대 20MB까지 지원합니다. 선명한 낮 시간대의 건축·조경 사진일수록 결과가 좋습니다.",

    // -- Blog page（한국어 글은 아직 없음. langsWithBlog 에 ko 를 넣으면 메뉴가 나타난다）--
    "blog.heading": "블로그",
    "blog.subtitle": "조명 시각화, AI 렌더링 워크플로, 야간경관 계획에 대한 실무 가이드.",
    "blog.empty": "아직 게시된 글이 없습니다. 곧 업데이트됩니다.",
    "blog.backToBlog": "← 블로그 목록으로",

    // -- Use Cases index --
    "useCases.heading": "디자이너들은 LDR을 이렇게 씁니다",
    "useCases.subtitle": "네 가지 분야, 하나의 공통 과제 — 등기구를 한 대도 설치하기 전에 발주처는 밤의 모습을 확인하고 싶어 합니다. LDR이 그 간극을 메웁니다.",
    "useCases.learnMore": "자세히 보기 →",
    "useCases.arch.title": "건축조명",
    "useCases.arch.desc": "파사드 조명, 캐노피 조명, 역사적 건축물 조명을 시공 전에 시각화합니다. 건축가, 조명 컨설턴트, 설계시공 업체를 위한 기능입니다.",
    "useCases.arch.keywords": "파사드 · 출입구 · 역사적 건축물",
    "useCases.landscape.title": "조경조명",
    "useCases.landscape.desc": "정원 업라이팅, 보행로 조명, 수경시설 조명을 미리 확인합니다. 조경건축가와 주거단지 설계자를 위한 기능입니다.",
    "useCases.landscape.keywords": "정원 · 보행로 · 수경시설",
    "useCases.urban.title": "야간경관 계획",
    "useCases.urban.desc": "도시 규모의 야간 환경, 교량 조명, 공공공간 조명을 시뮬레이션합니다. 도시계획가, 공공디자인 담당자, 지자체 컨설턴트를 위한 기능입니다.",
    "useCases.urban.keywords": "교량 · 공공공간 · 도시디자인",
    "useCases.hospitality.title": "호스피탈리티 조명",
    "useCases.hospitality.desc": "호텔 파사드, 풀 데크, 루프톱 바, 레스토랑 분위기를 렌더링합니다. 호스피탈리티 조명 컨설턴트와 브랜드 팀을 위한 기능입니다.",
    "useCases.hospitality.keywords": "호텔 · 리조트 · 레스토랑 · 바",
    "useCases.exploreOther": "다른 활용 사례 보기",

    // -- Meta --
    "meta.home.title": "AI 조명디자인 렌더링 — 낮에서 밤까지 몇 초 만에",
    "meta.home.desc": "AI로 낮 사진을 전문가급 야경 렌더링으로 바꿉니다. 사진을 올리고 조명 콘셉트를 설명하면 발표용 이미지가 바로 완성됩니다.",
    "meta.pricing.title": "요금제 — LDR 조명디자인 렌더링",
    "meta.pricing.desc": "AI 야경 렌더링의 간단한 요금제. 매일 1회 무료, 1회 결제 패키지는 $9부터, 월 구독은 $99부터(4K·워터마크 없음).",
    "meta.blog.title": "블로그 — 조명디자인과 AI 렌더링 실무 가이드",
    "meta.blog.desc": "AI 조명디자인 렌더링, 야경 시각화, 낮밤 변환에 대한 실무 가이드와 튜토리얼.",
    "meta.useCases.title": "활용 사례 — AI 조명디자인 렌더링",
    "meta.useCases.desc": "건축가, 조명디자이너, 도시계획가가 건축·조경·도시·호스피탈리티 프로젝트에서 LDR로 야경 렌더링을 만드는 방법을 소개합니다.",
  },

  /**
   * Deutsch —— für den deutschsprachigen Lichtplanungsmarkt (DE / AT / CH).
   *
   * Terminologie: an der Berufspraxis orientiert. "Lichtplanung" ist die
   * Berufsbezeichnung der Branche (Lichtplaner:in) und das Suchwort, nicht die
   * wörtliche Übersetzung "Lichtdesign". Weitere Ankerbegriffe: Fassadenbeleuchtung,
   * Nachtvisualisierung, Lichtkonzept, Farbtemperatur, Anstrahlung.
   * Anrede: durchgehend "Sie" (B2B-Standard).
   * Tarifnamen (Free / Mini / Pro / Max / Small / Standard / Large) bleiben englisch —
   * so heißen sie in der App und auf der Checkout-Seite.
   */
  de: {
    // -- Announcement --
    // Alipay ist für den deutschsprachigen Markt irrelevant → leer = wird nicht gerendert.
    "announcement.text": "",
    "announcement.dismiss": "Hinweis schließen",

    // -- Nav --
    "nav.useCases": "Anwendungen",
    "nav.pricing": "Preise",
    "nav.blog": "Blog",
    "nav.tryFree": "Kostenlos testen",
    "nav.toggleMenu": "Menü umschalten",

    // -- Footer --
    "footer.useCases": "Anwendungen",
    "footer.pricing": "Preise",
    "footer.blog": "Blog",
    "footer.app": "App",
    "footer.terms": "Nutzungsbedingungen",
    "footer.privacy": "Datenschutz",
    "footer.refund": "Rückerstattung",
    "footer.copyright": "© 2026 Alle Rechte vorbehalten.",
    "footer.navLabel": "Fußzeilen-Navigation",

    // -- OG --
    "og.siteName": "LDR – Lichtplanung & Nachtvisualisierung",

    // -- Hero --
    // 词中的 ­ 是软连字符：手机上标题必须断行，浏览器的德语断词词典会切成
    // "Nachtvi-sualisierungen"（合法但不在词素边界）。显式给出断点后是
    // "Nacht-visualisierungen"，符合德语复合词的断法。不影响正常显示与复制搜索。
    "hero.title": "Tagesfotos in professionelle Nacht­visualisierungen verwandeln",
    "hero.subtitle": "KI-gestützte Visualisierung für die Lichtplanung. Laden Sie ein Tagesfoto hoch und erhalten Sie in Sekunden ein professionelles Nachtrendering.",
    "hero.cta": "Kostenlos rendern",
    "hero.examples": "Beispiele ansehen",
    "hero.day": "Tag",
    "hero.night": "Nacht",
    "hero.fallback": "Vorher-Nachher-Beispiele finden Sie weiter unten",
    "hero.scrollGallery": "Zur Galerie scrollen",
    "hero.altDay": "Tagesaufnahme von",
    "hero.altNight": "KI-Nachtvisualisierung von",

    // -- Features --
    "features.heading": "Warum LDR?",
    "features.speed.title": "Vom Tag zur Nacht in Sekunden",
    "features.speed.desc": "Laden Sie ein beliebiges Tagesfoto einer Architektur oder Landschaft hoch und erhalten Sie sofort ein professionelles Nachtrendering.",
    "features.ai.title": "Präzision durch KI",
    "features.ai.desc": "Unsere KI erfasst den architektonischen Kontext, Materialeigenschaften und die Physik des Lichts – für glaubwürdige Ergebnisse.",
    "features.seg.title": "Semantische Segmentierung",
    "features.seg.desc": "Intelligente Szenenanalyse mit HQ-SAM trennt Gebäude, Himmel und Vegetation automatisch.",
    "features.quality.title": "4K in Profiqualität",
    "features.quality.desc": "Publikationsreife Renderings mit bis zu 4096 px Auflösung. In allen Bezahltarifen ohne Wasserzeichen.",

    // -- How It Works --
    "how.heading": "So funktioniert es",
    "how.step1.title": "Hochladen",
    "how.step1.desc": "Laden Sie ein Tagesfoto eines Gebäudes, einer Landschaft oder eines Stadtraums hoch",
    "how.step2.title": "Beschreiben",
    "how.step2.desc": "Beschreiben Sie der KI Ihr Lichtkonzept – oder lassen Sie sich einen Entwurf vorschlagen",
    "how.step3.title": "Rendern",
    "how.step3.desc": "In unter 60 Sekunden erhalten Sie Ihr professionelles Nachtrendering",

    // -- Showcase --
    "showcase.heading": "Ergebnisse ansehen",
    "showcase.empty": "Beispielbilder folgen in Kürze",
    "showcase.emptyDesc": "Professionelle Nachtrenderings, erzeugt mit LDR AI",

    // -- CTA --
    "cta.heading": "Bereit, Ihr Lichtkonzept sichtbar zu machen?",
    "cta.subtitle": "Schließen Sie sich den Planerinnen und Planern an, die Nachtbeleuchtung mit KI visualisieren.",
    "cta.button": "Kostenlos starten",
    "cta.note": "Keine Kreditkarte erforderlich · 1 kostenloses Rendering pro Tag",

    // -- Pricing --
    "pricing.heading": "Klare, transparente Preise",
    "pricing.subtitle": "Pro Projekt zahlen oder abonnieren · Weltweite Preise in USD · Kreditkarte / Apple Pay / Google Pay",
    "pricing.subSection": "Test & Abonnements",
    "pricing.subSectionDesc": "Vom kostenlosen Test bis zum Monatsabo · jederzeit wechselbar",
    "pricing.packSection": "Projektpakete",
    "pricing.packSectionDesc": "Pro Projekt kaufen · kein Abo · Paket-Credits verfallen nie",
    "pricing.popular": "Am beliebtesten",
    "pricing.disclaimer": "Projektpakete sind nach dem Kauf nicht erstattungsfähig (die Credits verfallen nie). Abonnements können jederzeit gekündigt werden; für die laufende Abrechnungsperiode erfolgt keine Rückerstattung. Alle Preise in USD, zuzüglich der je nach Region anfallenden Umsatzsteuer.",
    // Plan names (bleiben englisch – so heißen sie in App und Checkout)
    "pricing.free.name": "Free",
    "pricing.mini.name": "Mini",
    "pricing.pro.name": "Pro",
    "pricing.max.name": "Max",
    "pricing.small.name": "Small",
    "pricing.standard.name": "Standard",
    "pricing.large.name": "Large",
    // Periods
    "pricing.period.forever": "dauerhaft",
    "pricing.period.oneTime": "einmalig",
    "pricing.period.month": "Monat",
    // Euro-Richtwert (Stand 2026-08-10, gerechnet mit 1 USD ≈ 0,88 €, gerundet)
    "pricing.free.localPrice": "",
    "pricing.mini.localPrice": "ca. 8 €",
    "pricing.pro.localPrice": "ca. 87 €/Monat",
    "pricing.max.localPrice": "ca. 219 €/Monat",
    "pricing.small.localPrice": "ca. 52 €",
    "pricing.standard.localPrice": "ca. 114 €",
    "pricing.large.localPrice": "ca. 263 €",
    // Plans
    "pricing.free.tagline": "Erst testen, dann entscheiden",
    "pricing.free.f1": "5 Credits bei der Anmeldung",
    "pricing.free.f2": "1 kostenlose Generierung pro Tag",
    "pricing.free.f3": "1K-Auflösung mit Wasserzeichen",
    "pricing.free.f4": "Alle Funktionen nutzbar (Canvas + Chat)",
    "pricing.free.cta": "Jetzt starten",
    "pricing.mini.tagline": "Der Einstieg – Profiqualität ausprobieren",
    "pricing.mini.f1": "5 Credits (ca. 2–3 Bilder in 4K)",
    "pricing.mini.f2": "4K-Auflösung, ohne Wasserzeichen",
    "pricing.mini.f3": "Alle Funktionen freigeschaltet",
    "pricing.mini.f4": "Credits verfallen nie",
    "pricing.mini.cta": "Mini kaufen",
    "pricing.pro.tagline": "Laufender Betrieb – 2–3 Projekte pro Monat",
    "pricing.pro.f1": "120 Credits / Monat (ca. 60 Bilder in 4K)",
    "pricing.pro.f2": "Stapelverarbeitung (5 parallel)",
    "pricing.pro.f3": "Priorisierte Warteschlange",
    "pricing.pro.f4": "4K ohne Wasserzeichen · voller Funktionsumfang",
    "pricing.pro.f5": "Jederzeit kündbar, keine Folgekosten",
    "pricing.pro.cta": "Pro abonnieren",
    "pricing.max.tagline": "Teams – ab 10 Projekten pro Monat",
    "pricing.max.f1": "400 Credits / Monat (ca. 200 Bilder in 4K)",
    "pricing.max.f2": "Stapelverarbeitung + Priorität",
    "pricing.max.f3": "API-Zugang",
    "pricing.max.f4": "Bevorzugter E-Mail-Support",
    "pricing.max.f5": "Jederzeit kündbar, keine Folgekosten",
    "pricing.max.cta": "Max abonnieren",
    "pricing.small.tagline": "Ein kleines Projekt, 5–10 Bilder",
    "pricing.small.f1": "30 Credits (ca. 15 Bilder in 4K)",
    "pricing.small.f2": "4K ohne Wasserzeichen",
    "pricing.small.f3": "Canvas-Editor + Chat-Agent",
    "pricing.small.f4": "Credits verfallen nie",
    "pricing.small.cta": "Small kaufen",
    "pricing.standard.tagline": "Passt für ein Projekt mit 14 Bildern",
    "pricing.standard.f1": "80 Credits (ca. 40 Bilder in 4K)",
    "pricing.standard.f2": "Iteratives Feintuning im Canvas",
    "pricing.standard.f3": "Alle Funktionen + Kanaldiagramm",
    "pricing.standard.f4": "Credits verfallen nie",
    "pricing.standard.cta": "Standard kaufen",
    "pricing.large.tagline": "Mehrere Iterationsrunden oder 50+ Bilder",
    "pricing.large.f1": "250 Credits (ca. 125 Bilder in 4K)",
    "pricing.large.f2": "Canvas + Chat + Kanaldiagramm",
    "pricing.large.f3": "Bevorzugte Support-Reaktion",
    "pricing.large.f4": "Credits verfallen nie",
    "pricing.large.cta": "Large kaufen",

    // -- Pricing FAQ --
    "faq.heading": "Häufige Fragen",
    "faq.q1": "Kann ich LDR kostenlos testen?",
    "faq.a1": "Ja. Jedes Konto erhält bei der Anmeldung 5 Credits und zusätzlich täglich ein kostenloses Rendering in 1K-Auflösung. Eine Kreditkarte ist dafür nicht erforderlich.",
    "faq.q2": "Worin unterscheiden sich Projektpaket und Abonnement?",
    "faq.a2": "Projektpakete (Mini, Small, Standard, Large) sind Einmalkäufe mit einem festen Credit-Kontingent, das nie verfällt – die richtige Wahl, wenn ein konkretes Projekt ansteht. Abonnements (Pro, Max) verlängern sich monatlich und stellen in jedem Zyklus frische Credits bereit – sinnvoll bei kontinuierlicher Auslastung. Beides lässt sich kombinieren: Sie können abonnieren und für ein großes Projekt zusätzlich ein Paket kaufen.",
    "faq.q3": "In welcher Auflösung wird gerendert?",
    "faq.a3": "Der kostenlose Tarif rendert in 1K mit Wasserzeichen. Alle Bezahltarife (Mini, Small, Standard, Large, Pro, Max) rendern mit bis zu 4K (4096 px) ohne Wasserzeichen – geeignet für Präsentationen und Publikationen.",
    "faq.q4": "Verfallen nicht genutzte Paket-Credits?",
    "faq.a4": "Nein. Paket-Credits verfallen nie und bleiben in Ihrem Konto, bis Sie sie verbrauchen. Abo-Credits werden zu jedem Abrechnungszyklus erneuert und nicht in den Folgemonat übertragen.",
    "faq.q5": "Kann ich mein Abonnement kündigen?",
    "faq.a5": "Ja, jederzeit über das Kundenportal. Das Abonnement bleibt bis zum Ende der laufenden Abrechnungsperiode aktiv; für den nicht genutzten Teil dieser Periode erfolgt keine Rückerstattung.",
    "faq.q6": "Sind Projektpakete erstattungsfähig?",
    "faq.a6": "Projektpakete sind nach dem Kauf nicht erstattungsfähig. Die Credits verfallen nie und bleiben verfügbar, bis Sie sie einsetzen. Für das erste Abonnement kann eine 7-tägige Geld-zurück-Garantie gelten – Einzelheiten dazu in unserer ",
    "faq.a6.link": "Rückerstattungsrichtlinie",
    "faq.a6.suffix": ".",
    "faq.q7": "Welche Zahlungsmethoden werden unterstützt?",
    "faq.a7": "LDR nutzt Creem Inc. als Merchant of Record. Verfügbar sind derzeit gängige Kreditkarten, Apple Pay und Google Pay – die konkreten Optionen können je nach Region abweichen; maßgeblich ist die Auswahl auf der Checkout-Seite. Alle Preise verstehen sich in USD und werden beim Bezahlen automatisch in Ihre Landeswährung umgerechnet.",
    "faq.q8": "Welche Bildformate werden unterstützt?",
    "faq.a8": "Wir akzeptieren JPG, PNG und WebP bis 20 MB. Die besten Ergebnisse liefern klare Tagesaufnahmen von Architektur oder Landschaft.",

    // -- Blog page (deutsche Beiträge stehen noch aus – siehe langsWithBlog) --
    "blog.heading": "Blog",
    "blog.subtitle": "Praxisleitfäden zu Lichtvisualisierung, KI-Rendering-Workflows und Nachtplanung.",
    "blog.empty": "Noch keine Beiträge veröffentlicht. Schauen Sie bald wieder vorbei.",
    "blog.backToBlog": "← Zurück zum Blog",

    // -- Use Cases index --
    "useCases.heading": "So arbeiten Planer mit LDR",
    "useCases.subtitle": "Vier Disziplinen, ein gemeinsames Problem: Bauherren müssen die Nachtwirkung sehen, bevor die erste Leuchte montiert ist. LDR schließt genau diese Lücke.",
    "useCases.learnMore": "Mehr erfahren →",
    "useCases.arch.title": "Architekturbeleuchtung",
    "useCases.arch.desc": "Fassadenbeleuchtung, Eingangsüberdachungen und Denkmalbeleuchtung schon vor der Montage sichtbar machen. Für Architektinnen, Lichtplaner und Generalunternehmer.",
    "useCases.arch.keywords": "Fassaden · Eingänge · Denkmalschutz",
    "useCases.landscape.title": "Landschaftsbeleuchtung",
    "useCases.landscape.desc": "Anstrahlung im Garten, Wegebeleuchtung und beleuchtete Wasserflächen vorab beurteilen. Für Landschaftsarchitekten und Planer hochwertiger Wohnanlagen.",
    "useCases.landscape.keywords": "Gärten · Wege · Wasserflächen",
    "useCases.urban.title": "Städtische Nachtplanung",
    "useCases.urban.desc": "Nächtliche Stadträume, Brückenbeleuchtung und öffentliche Räume im Stadtmaßstab durchspielen. Für Stadtplanerinnen, Gestaltungsbeiräte und kommunale Berater.",
    "useCases.urban.keywords": "Brücken · Öffentlicher Raum · Stadtgestaltung",
    "useCases.hospitality.title": "Hotellerie & Gastronomie",
    "useCases.hospitality.desc": "Hotelfassaden, Poolterrassen, Rooftop-Bars und die Atmosphäre von Boutique-Restaurants rendern. Für Lichtplaner und Markenteams im Gastgewerbe.",
    "useCases.hospitality.keywords": "Hotels · Resorts · Restaurants · Bars",
    "useCases.exploreOther": "Weitere Anwendungen",

    // -- Meta --
    "meta.home.title": "KI-Rendering für die Lichtplanung – vom Tag zur Nacht in Sekunden",
    "meta.home.desc": "Verwandeln Sie Tagesfotos mit KI in professionelle Nachtvisualisierungen. Foto hochladen, Lichtkonzept beschreiben, publikationsreifes Rendering erhalten.",
    "meta.pricing.title": "Preise – LDR Rendering für die Lichtplanung",
    "meta.pricing.desc": "Transparente Preise für KI-Nachtrenderings. Kostenlos starten mit 1 Rendering pro Tag, Einmalpakete ab 9 $ oder Abo ab 99 $/Monat für 4K ohne Wasserzeichen.",
    "meta.blog.title": "Blog – Lichtplanung und KI-Rendering in der Praxis",
    "meta.blog.desc": "Praxisleitfäden, Tutorials und Tipps zu KI-gestütztem Rendering für die Lichtplanung, Nachtvisualisierung und Tag-Nacht-Umwandlung.",
    "meta.useCases.title": "Anwendungen – KI-Rendering für die Lichtplanung",
    "meta.useCases.desc": "Wie Architekten, Lichtplaner und Stadtplanerinnen mit LDR Nachtvisualisierungen für Architektur-, Landschafts-, Stadt- und Hotelprojekte erstellen.",
  },
  ar: {
    // -- Announcement（顶部公告条）--
    "announcement.text": "",
    "announcement.dismiss": "إغلاق الإعلان",

    // -- Nav --
    "nav.useCases": "مجالات الاستخدام",
    "nav.pricing": "الأسعار",
    "nav.blog": "المدونة",
    "nav.tryFree": "جرّب مجانًا",
    "nav.toggleMenu": "فتح القائمة",

    // -- Footer --
    "footer.useCases": "مجالات الاستخدام",
    "footer.pricing": "الأسعار",
    "footer.blog": "المدونة",
    "footer.app": "التطبيق",
    "footer.terms": "شروط الخدمة",
    "footer.privacy": "سياسة الخصوصية",
    "footer.refund": "سياسة الاسترداد",
    "footer.copyright": "© 2026 جميع الحقوق محفوظة.",
    "footer.navLabel": "روابط التذييل",

    // -- OG --
    "og.siteName": "LDR - الإظهار الليلي لتصميم الإضاءة",

    // -- Hero --
    "hero.title": "حوّل الصور النهارية إلى إظهارات ليلية احترافية",
    "hero.subtitle": "تصوّر لتصميم الإضاءة مدعوم بالذكاء الاصطناعي. ارفع صورة نهارية واحصل على إظهار ليلي احترافي خلال ثوانٍ.",
    "hero.cta": "ابدأ الإظهار مجانًا",
    "hero.examples": "شاهد الأمثلة",
    "hero.day": "نهارًا",
    "hero.night": "ليلًا",
    "hero.fallback": "شاهد أمثلة قبل/بعد في الأسفل",
    "hero.scrollGallery": "انتقل إلى المعرض",
    "hero.altDay": "صورة نهارية لـ",
    "hero.altNight": "إظهار ليلي بالذكاء الاصطناعي لـ",

    // -- Features --
    "features.heading": "لماذا LDR؟",
    "features.speed.title": "من النهار إلى الليل خلال ثوانٍ",
    "features.speed.desc": "ارفع أي صورة نهارية لمبنى أو موقع واحصل على إظهار ليلي احترافي فورًا.",
    "features.ai.title": "دقة مدعومة بالذكاء الاصطناعي",
    "features.ai.desc": "يفهم النظام السياق المعماري وخصائص المواد وفيزياء الضوء ليخرج بنتائج واقعية.",
    "features.seg.title": "تجزئة دلالية للمشهد",
    "features.seg.desc": "فهم ذكي للمشهد بتقنية HQ-SAM يفصل المباني والسماء والغطاء النباتي تلقائيًا.",
    "features.quality.title": "إخراج احترافي بدقة 4K",
    "features.quality.desc": "إظهارات جاهزة للنشر حتى دقة 4096 بكسل، وبلا علامة مائية في الباقات المدفوعة.",

    // -- How It Works --
    "how.heading": "كيف يعمل",
    "how.step1.title": "ارفع الصورة",
    "how.step1.desc": "ارفع صورة نهارية لأي مبنى أو موقع أو مشهد حضري",
    "how.step2.title": "صف الإضاءة",
    "how.step2.desc": "اشرح رؤيتك للإضاءة، أو دع الذكاء الاصطناعي يقترح التصميم المناسب",
    "how.step3.title": "احصل على الإظهار",
    "how.step3.desc": "استلم الإظهار الليلي الاحترافي في أقل من 60 ثانية",

    // -- Showcase --
    "showcase.heading": "شاهد النتائج",
    "showcase.empty": "صور المعرض قريبًا",
    "showcase.emptyDesc": "إظهارات ليلية احترافية من إنتاج LDR",

    // -- CTA --
    "cta.heading": "جاهز لتحويل تصاميم الإضاءة لديك؟",
    "cta.subtitle": "انضم إلى المصممين والمعماريين الذين يستخدمون الذكاء الاصطناعي لتصوّر الإضاءة الليلية.",
    "cta.button": "ابدأ مجانًا",
    "cta.note": "بدون بطاقة ائتمان • إظهار مجاني واحد يوميًا",

    // -- Pricing --
    "pricing.heading": "أسعار بسيطة وواضحة",
    "pricing.subtitle": "ادفع لكل مشروع أو اشترك للعمل المستمر · تسعير عالمي بالدولار الأمريكي · بطاقات / Apple Pay / Google Pay · Alipay للباقات ذات الدفعة الواحدة",
    "pricing.subSection": "التجربة والاشتراكات",
    "pricing.subSectionDesc": "من التجربة المجانية إلى الاشتراكات الشهرية · يمكنك الترقية في أي وقت",
    "pricing.packSection": "باقات المشاريع",
    "pricing.packSectionDesc": "اشترِ حسب المشروع · بلا اشتراك · رصيد الباقات لا ينتهي",
    "pricing.popular": "الأكثر اختيارًا",
    "pricing.disclaimer": "الباقات غير قابلة للاسترداد (والرصيد لا ينتهي). يمكن إلغاء الاشتراك في أي وقت دون استرداد قيمة الفترة الجارية.",
    // Plan names —— 与 ja/ko/de 一致，套餐名是产品 SKU，不翻译
    "pricing.free.name": "Free",
    "pricing.mini.name": "Mini",
    "pricing.pro.name": "Pro",
    "pricing.max.name": "Max",
    "pricing.small.name": "Small",
    "pricing.standard.name": "Standard",
    "pricing.large.name": "Large",
    // Periods
    "pricing.period.forever": "دائمًا",
    "pricing.period.oneTime": "دفعة واحدة",
    "pricing.period.month": "شهريًا",
    // 本币参考价留空：阿语覆盖多国（AED/SAR/QAR/KWD/EGP），
    // 挑任一国的货币对其他国家都别扭，且 AED 与 SAR 本就与美元挂钩，换算无信息增量。
    "pricing.free.localPrice": "",
    "pricing.mini.localPrice": "",
    "pricing.pro.localPrice": "",
    "pricing.max.localPrice": "",
    "pricing.small.localPrice": "",
    "pricing.standard.localPrice": "",
    "pricing.large.localPrice": "",
    // Plans
    "pricing.free.tagline": "جرّب قبل الشراء",
    "pricing.free.f1": "5 أرصدة عند التسجيل",
    "pricing.free.f2": "إظهار مجاني واحد يوميًا",
    "pricing.free.f3": "دقة 1K مع علامة مائية",
    "pricing.free.f4": "كل الميزات متاحة (Canvas + Chat)",
    "pricing.free.cta": "ابدأ الآن",
    "pricing.mini.tagline": "أول باقة مدفوعة — جرّب الجودة التجارية",
    "pricing.mini.f1": "5 أرصدة (نحو 2-3 صور تجارية بدقة 4K)",
    "pricing.mini.f2": "دقة 4K بلا علامة مائية",
    "pricing.mini.f3": "كل الميزات مفتوحة",
    "pricing.mini.f4": "الرصيد لا ينتهي",
    "pricing.mini.cta": "اشترِ Mini",
    "pricing.pro.tagline": "عمل مستمر — من 2 إلى 3 مشاريع شهريًا",
    "pricing.pro.f1": "120 رصيدًا شهريًا (نحو 60 صورة 4K)",
    "pricing.pro.f2": "توليد دفعي (5 صور بالتوازي)",
    "pricing.pro.f3": "أولوية في طابور التوليد",
    "pricing.pro.f4": "4K بلا علامة مائية · كل الميزات",
    "pricing.pro.f5": "ألغِ في أي وقت دون رسوم للدورة التالية",
    "pricing.pro.cta": "اشترك في Pro",
    "pricing.max.tagline": "للفرق — أكثر من 10 مشاريع شهريًا",
    "pricing.max.f1": "400 رصيد شهريًا (نحو 200 صورة 4K)",
    "pricing.max.f2": "توليد دفعي وأولوية في الطابور",
    "pricing.max.f3": "وصول إلى واجهة البرمجة (API)",
    "pricing.max.f4": "دعم بالبريد ذو أولوية",
    "pricing.max.f5": "ألغِ في أي وقت دون رسوم للدورة التالية",
    "pricing.max.cta": "اشترك في Max",
    "pricing.small.tagline": "مشروع صغير واحد، من 5 إلى 10 صور",
    "pricing.small.f1": "30 رصيدًا (نحو 15 صورة 4K)",
    "pricing.small.f2": "4K بلا علامة مائية",
    "pricing.small.f3": "محرر Canvas و Chat Agent",
    "pricing.small.f4": "الرصيد لا ينتهي",
    "pricing.small.cta": "اشترِ Small",
    "pricing.standard.tagline": "يكفي مشروعًا تجاريًا من 14 صورة",
    "pricing.standard.f1": "80 رصيدًا (نحو 40 صورة 4K)",
    "pricing.standard.f2": "تحسين تكراري على Canvas",
    "pricing.standard.f3": "كل الميزات + مخطط القنوات اللونية",
    "pricing.standard.f4": "الرصيد لا ينتهي",
    "pricing.standard.cta": "اشترِ Standard",
    "pricing.large.tagline": "تكرارات متعددة أو أكثر من 50 صورة",
    "pricing.large.f1": "250 رصيدًا (نحو 125 صورة 4K)",
    "pricing.large.f2": "Canvas و Chat ومخطط القنوات اللونية",
    "pricing.large.f3": "أولوية في الرد والدعم",
    "pricing.large.f4": "الرصيد لا ينتهي",
    "pricing.large.cta": "اشترِ Large",

    // -- Pricing FAQ --
    "faq.heading": "الأسئلة الشائعة",
    "faq.q1": "هل يمكنني تجربة LDR مجانًا؟",
    "faq.a1": "نعم. كل حساب يحصل على 5 أرصدة عند التسجيل، بالإضافة إلى إظهار مجاني واحد يوميًا بدقة 1K. لا حاجة إلى بطاقة ائتمان.",
    "faq.q2": "ما الفرق بين الباقة والاشتراك؟",
    "faq.a2": "الباقات (Mini وSmall وStandard وLarge) عمليات شراء لمرة واحدة برصيد ثابت لا ينتهي، وتناسبك عندما يكون لديك مشروع محدد. أما الاشتراكات (Pro وMax) فتتجدد شهريًا برصيد جديد كل دورة، وهي الأنسب إن كان لديك عمل مستمر. ويمكنك الجمع بينهما: اشترك، ثم اشترِ باقة إضافية عند وصول مشروع كبير.",
    "faq.q3": "ما دقة الصور الناتجة؟",
    "faq.a3": "الباقة المجانية تُخرج بدقة 1K مع علامة مائية. أما الباقات المدفوعة كلها (Mini وSmall وStandard وLarge وPro وMax) فتُخرج حتى دقة 4K (4096 بكسل) بلا علامة مائية، وهي مناسبة للعروض التقديمية والنشر الاحترافي.",
    "faq.q4": "هل ينتهي رصيد الباقات غير المستخدم؟",
    "faq.a4": "لا. رصيد الباقات لا ينتهي أبدًا ويبقى في حسابك حتى تستخدمه. أما رصيد الاشتراك فيتجدد كل دورة فوترة ولا يُرحَّل إلى الدورة التالية.",
    "faq.q5": "هل يمكنني إلغاء الاشتراك؟",
    "faq.a5": "نعم، يمكنك الإلغاء في أي وقت من بوابة العملاء. يبقى اشتراكك فعّالًا حتى نهاية فترة الفوترة الجارية، ولا يوجد استرداد للجزء غير المستخدم من تلك الفترة.",
    "faq.q6": "هل الباقات قابلة للاسترداد؟",
    "faq.a6": "الباقات غير قابلة للاسترداد بعد الشراء. والرصيد لا ينتهي، فيبقى متاحًا حتى تستخدمه. وقد يكون المشتركون الجدد مؤهلين لضمان استرداد خلال 7 أيام على أول اشتراك لهم — راجع ",
    "faq.a6.link": "سياسة الاسترداد",
    "faq.a6.suffix": " لمعرفة التفاصيل.",
    "faq.q7": "ما طرق الدفع المدعومة؟",
    "faq.a7": "تعتمد LDR على شركة Creem Inc. بصفتها التاجر المسجَّل. تشمل الطرق المتاحة حاليًا بطاقات الائتمان الكبرى وAlipay وApple Pay وGoogle Pay، وقد تختلف الخيارات من منطقة إلى أخرى، والطرق الظاهرة في صفحة الدفع هي المرجع. تتوفر Alipay لعمليات الشراء لمرة واحدة فقط، أما الاشتراكات فتتطلب بطاقة أو Apple Pay أو Google Pay. جميع الأسعار بالدولار الأمريكي، ويجري تحويل العملة المحلية تلقائيًا عند الدفع.",
    "faq.q8": "ما صيغ الصور المدعومة؟",
    "faq.a8": "نقبل صيغ JPG وPNG وWebP بحجم يصل إلى 20 ميغابايت. ويعطي النظام أفضل نتائجه مع صور نهارية واضحة للمباني أو المواقع.",

    // -- Blog page --
    "blog.heading": "المدونة",
    "blog.subtitle": "أدلة عملية في تصور تصميم الإضاءة، وسير عمل الإظهار بالذكاء الاصطناعي، وتخطيط المشهد الليلي.",
    "blog.empty": "لا توجد مقالات منشورة بعد. عد إلينا قريبًا.",
    "blog.backToBlog": "→ العودة إلى المدونة",

    // -- Use Cases index --
    "useCases.heading": "كيف يستخدم المصممون LDR",
    "useCases.subtitle": "أربعة تخصصات، ومشكلة واحدة مشتركة: العميل يحتاج أن يرى الإضاءة الليلية قبل تركيب أي وحدة إنارة. وLDR يسدّ هذه الفجوة لكل منها.",
    "useCases.learnMore": "اعرف المزيد ←",
    "useCases.arch.title": "إضاءة العمارة",
    "useCases.arch.desc": "تصوَّر إضاءة الواجهات ومظلات المداخل وإضاءة المباني التراثية قبل التركيب. للمعماريين واستشاريي الإضاءة ومقاولي التصميم والتنفيذ.",
    "useCases.arch.keywords": "الواجهات · المداخل · المباني التراثية",
    "useCases.landscape.title": "إضاءة المواقع والحدائق",
    "useCases.landscape.desc": "عاين الإضاءة الصاعدة في الحدائق وإضاءة الممرات والعناصر المائية. لمعماريي المواقع ومصممي الاستراحات والمساكن الخاصة.",
    "useCases.landscape.keywords": "الحدائق · الممرات · العناصر المائية",
    "useCases.urban.title": "التخطيط الليلي للمدن",
    "useCases.urban.desc": "امذجة البيئة الليلية على مستوى المدينة، وإضاءة الجسور والفضاءات العامة. لمخططي المدن ومصممي المرافق العامة والاستشاريين البلديين.",
    "useCases.urban.keywords": "الجسور · الفضاء العام · المرافق المدنية",
    "useCases.hospitality.title": "إضاءة الضيافة",
    "useCases.hospitality.desc": "أظهر واجهات الفنادق وأسطح المسابح وبارات الأسطح وأجواء المطاعم البوتيكية. لاستشاريي إضاءة الضيافة وفرق العلامات التجارية.",
    "useCases.hospitality.keywords": "الفنادق · المنتجعات · المطاعم · البارات",
    "useCases.exploreOther": "استكشف مجالات أخرى",

    // -- Meta (page titles / descriptions) --
    "meta.home.title": "إظهار الإضاءة بالذكاء الاصطناعي — من النهار إلى الليل",
    "meta.home.desc": "حوّل الصور النهارية إلى تصورات ليلية احترافية بالذكاء الاصطناعي. ارفع صورة، وصف رؤيتك للإضاءة، واحصل على إظهار جاهز للنشر خلال ثوانٍ.",
    "meta.pricing.title": "الأسعار — LDR للإظهار الليلي لتصميم الإضاءة",
    "meta.pricing.desc": "أسعار واضحة للإظهار الليلي بالذكاء الاصطناعي. ابدأ مجانًا بإظهار يومي، أو باقة لمرة واحدة من 9 دولارات، أو اشتراك من 99 دولارًا لإخراج 4K بلا علامة مائية.",
    "meta.blog.title": "المدونة — أدلة تصميم الإضاءة والإظهار بالذكاء الاصطناعي",
    "meta.blog.desc": "أدلة عملية ودروس ونصائح في الإظهار الليلي بالذكاء الاصطناعي، وتصور تصميم الإضاءة، وتحويل الصور من النهار إلى الليل.",
    "meta.useCases.title": "مجالات الاستخدام — إظهار تصميم الإضاءة بالذكاء الاصطناعي",
    "meta.useCases.desc": "كيف يستخدم المعماريون ومصممو الإضاءة ومخططو المدن أداة LDR لإنتاج إظهارات ليلية لمشاريع العمارة والمواقع والمدن والضيافة.",
  },

  tr: {
    // -- Announcement（顶部公告条）--
    "announcement.text": "",
    "announcement.dismiss": "Duyuruyu kapat",

    // -- Nav --
    "nav.useCases": "Kullanım Alanları",
    "nav.pricing": "Fiyatlandırma",
    "nav.blog": "Blog",
    "nav.tryFree": "Ücretsiz Dene",
    "nav.toggleMenu": "Menüyü aç/kapat",

    // -- Footer --
    "footer.useCases": "Kullanım Alanları",
    "footer.pricing": "Fiyatlandırma",
    "footer.blog": "Blog",
    "footer.app": "Uygulama",
    "footer.terms": "Kullanım Koşulları",
    "footer.privacy": "Gizlilik Politikası",
    "footer.refund": "İade Politikası",
    "footer.copyright": "© 2026 Tüm hakları saklıdır.",
    "footer.navLabel": "Alt bilgi menüsü",

    // -- OG --
    "og.siteName": "LDR - Aydınlatma Tasarımı Görselleştirme",

    // -- Hero --
    "hero.title": "Gündüz Fotoğraflarını Profesyonel Gece Görselleştirmelerine Dönüştürün",
    "hero.subtitle": "Yapay zekâ destekli aydınlatma tasarımı görselleştirmesi. Bir gündüz fotoğrafı yükleyin, saniyeler içinde profesyonel bir gece görselleştirmesi alın.",
    "hero.cta": "Ücretsiz Başlayın",
    "hero.examples": "Örnekleri Görün",
    "hero.day": "Gündüz",
    "hero.night": "Gece",
    "hero.fallback": "Aşağıda öncesi/sonrası örneklerine bakın",
    "hero.scrollGallery": "Galeriye git",
    "hero.altDay": "Gündüz fotoğrafı:",
    "hero.altNight": "Yapay zekâ ile gece görselleştirmesi:",

    // -- Features --
    "features.heading": "Neden LDR?",
    "features.speed.title": "Saniyeler İçinde Gündüzden Geceye",
    "features.speed.desc": "Herhangi bir yapı veya peyzaj fotoğrafını yükleyin, anında profesyonel bir gece görselleştirmesi alın.",
    "features.ai.title": "Yapay Zekâ Hassasiyeti",
    "features.ai.desc": "Yapay zekâmız mimari bağlamı, malzeme özelliklerini ve ışığın fiziğini anlayarak gerçekçi sonuçlar üretir.",
    "features.seg.title": "Anlamsal Bölütleme",
    "features.seg.desc": "HQ-SAM teknolojisiyle akıllı sahne analizi; binaları, gökyüzünü ve bitki örtüsünü otomatik olarak ayırır.",
    "features.quality.title": "4K Profesyonel Çıktı",
    "features.quality.desc": "4096 piksele kadar, yayına hazır görseller. Ücretli paketlerde filigran yok.",

    // -- How It Works --
    "how.heading": "Nasıl Çalışır",
    "how.step1.title": "Yükleyin",
    "how.step1.desc": "Herhangi bir bina, peyzaj veya kent sahnesinin gündüz fotoğrafını yükleyin",
    "how.step2.title": "Tarif Edin",
    "how.step2.desc": "Aydınlatma fikrinizi anlatın ya da yapay zekânın tasarımı önermesine izin verin",
    "how.step3.title": "Görselleştirin",
    "how.step3.desc": "Profesyonel gece görselleştirmenizi 60 saniyenin altında alın",

    // -- Showcase --
    "showcase.heading": "Sonuçlara Bakın",
    "showcase.empty": "Galeri görselleri çok yakında",
    "showcase.emptyDesc": "LDR yapay zekâsıyla üretilmiş profesyonel gece görselleştirmeleri",

    // -- CTA --
    "cta.heading": "Aydınlatma Tasarımlarınızı Dönüştürmeye Hazır mısınız?",
    "cta.subtitle": "Gece aydınlatmasını görselleştirmek için yapay zekâ kullanan tasarımcılara ve mimarlara katılın.",
    "cta.button": "Ücretsiz Başlayın",
    "cta.note": "Kredi kartı gerekmez • Her gün 1 ücretsiz görselleştirme",

    // -- Pricing --
    "pricing.heading": "Basit ve Şeffaf Fiyatlandırma",
    "pricing.subtitle": "Proje başına ödeyin ya da süregelen iş için abone olun · Küresel USD fiyatlandırma · Kart / Apple Pay / Google Pay · Tek seferlik paketler için Alipay",
    "pricing.subSection": "Deneme ve Abonelikler",
    "pricing.subSectionDesc": "Ücretsiz denemeden aylık aboneliklere · dilediğiniz zaman yükseltin",
    "pricing.packSection": "Proje Paketleri",
    "pricing.packSectionDesc": "Proje başına satın alın · abonelik yok · paket kredileri süresiz",
    "pricing.popular": "En Çok Tercih Edilen",
    "pricing.disclaimer": "Paketler iade edilemez (krediler süresizdir). Abonelikler istediğiniz zaman iptal edilebilir; içinde bulunulan dönem için iade yapılmaz.",
    // Plan names —— 与 ja/ko/de 一致，套餐名是产品 SKU，不翻译
    "pricing.free.name": "Free",
    "pricing.mini.name": "Mini",
    "pricing.pro.name": "Pro",
    "pricing.max.name": "Max",
    "pricing.small.name": "Small",
    "pricing.standard.name": "Standard",
    "pricing.large.name": "Large",
    // Periods
    "pricing.period.forever": "süresiz",
    "pricing.period.oneTime": "tek seferlik",
    "pricing.period.month": "ay",
    // 本币参考价留空：里拉波动大，写死的换算几周就过期，比不显示更糟。以 USD 为准。
    "pricing.free.localPrice": "",
    "pricing.mini.localPrice": "",
    "pricing.pro.localPrice": "",
    "pricing.max.localPrice": "",
    "pricing.small.localPrice": "",
    "pricing.standard.localPrice": "",
    "pricing.large.localPrice": "",
    // Plans
    "pricing.free.tagline": "Satın almadan önce deneyin",
    "pricing.free.f1": "Kayıtta 5 kredi",
    "pricing.free.f2": "Her gün 1 ücretsiz üretim",
    "pricing.free.f3": "Filigranlı 1K çözünürlük",
    "pricing.free.f4": "Tüm özellikler açık (Canvas + Chat)",
    "pricing.free.cta": "Başlayın",
    "pricing.mini.tagline": "İlk ücretli paket — ticari kaliteyi deneyin",
    "pricing.mini.f1": "5 kredi (~2-3 adet 4K ticari görsel)",
    "pricing.mini.f2": "4K çözünürlük, filigransız",
    "pricing.mini.f3": "Tüm özellikler açık",
    "pricing.mini.f4": "Krediler süresiz",
    "pricing.mini.cta": "Mini Satın Al",
    "pricing.pro.tagline": "Süregelen iş — ayda 2-3 proje",
    "pricing.pro.f1": "Ayda 120 kredi (~60 adet 4K görsel)",
    "pricing.pro.f2": "Toplu üretim (5 paralel)",
    "pricing.pro.f3": "Öncelikli üretim kuyruğu",
    "pricing.pro.f4": "4K filigransız · tüm özellikler",
    "pricing.pro.f5": "İstediğiniz zaman iptal, sonraki dönem ücreti yok",
    "pricing.pro.cta": "Pro'ya Abone Ol",
    "pricing.max.tagline": "Ekipler — ayda 10+ proje",
    "pricing.max.f1": "Ayda 400 kredi (~200 adet 4K görsel)",
    "pricing.max.f2": "Toplu üretim + öncelikli kuyruk",
    "pricing.max.f3": "API erişimi",
    "pricing.max.f4": "Öncelikli e-posta desteği",
    "pricing.max.f5": "İstediğiniz zaman iptal, sonraki dönem ücreti yok",
    "pricing.max.cta": "Max'e Abone Ol",
    "pricing.small.tagline": "Tek küçük proje, 5-10 görsel",
    "pricing.small.f1": "30 kredi (~15 adet 4K görsel)",
    "pricing.small.f2": "4K filigransız",
    "pricing.small.f3": "Canvas editörü + Chat Agent",
    "pricing.small.f4": "Krediler süresiz",
    "pricing.small.cta": "Small Satın Al",
    "pricing.standard.tagline": "14 görsellik ticari bir projeye yeter",
    "pricing.standard.f1": "80 kredi (~40 adet 4K görsel)",
    "pricing.standard.f2": "Canvas ile yinelemeli iyileştirme",
    "pricing.standard.f3": "Tüm özellikler + Kanal diyagramı",
    "pricing.standard.f4": "Krediler süresiz",
    "pricing.standard.cta": "Standard Satın Al",
    "pricing.large.tagline": "Çok turlu yineleme veya 50+ görsel",
    "pricing.large.f1": "250 kredi (~125 adet 4K görsel)",
    "pricing.large.f2": "Canvas + Chat + Kanal diyagramı",
    "pricing.large.f3": "Öncelikli destek yanıtı",
    "pricing.large.f4": "Krediler süresiz",
    "pricing.large.cta": "Large Satın Al",

    // -- Pricing FAQ --
    "faq.heading": "Sıkça Sorulan Sorular",
    "faq.q1": "LDR'yi ücretsiz deneyebilir miyim?",
    "faq.a1": "Evet. Her hesap kayıtta 5 kredi ve ardından her gün 1K çözünürlükte 1 ücretsiz görselleştirme alır. Kredi kartı gerekmez.",
    "faq.q2": "Paket ile abonelik arasındaki fark nedir?",
    "faq.a2": "Paketler (Mini, Small, Standard, Large) sabit sayıda ve süresiz krediyle tek seferlik satın alımlardır; belirli bir projeniz varsa bunları tercih edin. Abonelikler (Pro, Max) her ay yenilenir ve her dönem taze kredi verir — düzenli, süregelen işiniz varsa en uygunu budur. İkisini birlikte de kullanabilirsiniz: abone olun, büyük bir proje geldiğinde ayrıca paket alın.",
    "faq.q3": "Görsellerin çözünürlüğü nedir?",
    "faq.a3": "Ücretsiz paket 1K çözünürlükte ve filigranlı üretir. Tüm ücretli paketler (Mini, Small, Standard, Large, Pro, Max) 4K'ya (4096 piksel) kadar filigransız üretir; profesyonel sunumlar ve yayın için uygundur.",
    "faq.q4": "Kullanılmayan paket kredileri yanar mı?",
    "faq.a4": "Hayır. Paket kredilerinin süresi dolmaz; siz kullanana kadar hesabınızda kalır. Abonelik kredileri ise her fatura döneminde yenilenir ve sonraki döneme devretmez.",
    "faq.q5": "Aboneliğimi iptal edebilir miyim?",
    "faq.a5": "Evet, müşteri portalından dilediğiniz zaman iptal edebilirsiniz. Aboneliğiniz içinde bulunulan fatura döneminin sonuna kadar etkin kalır ve o dönemin kullanılmayan kısmı için iade yapılmaz.",
    "faq.q6": "Paketler iade edilebilir mi?",
    "faq.a6": "Paketler satın alındıktan sonra iade edilemez. Kredilerin süresi dolmadığı için siz kullanana kadar durur. Yeni aboneler ilk abonelikleri için 7 günlük para iade garantisinden yararlanabilir — ayrıntılar için ",
    "faq.a6.link": "İade Politikamıza",
    "faq.a6.suffix": " bakın.",
    "faq.q7": "Hangi ödeme yöntemleri destekleniyor?",
    "faq.a7": "LDR, kayıtlı satıcı olarak Creem Inc. ile çalışır. Şu anda başlıca kredi kartları, Alipay, Apple Pay ve Google Pay kullanılabilir; seçenekler bölgeye göre değişebilir ve ödeme sayfasında görünen yöntemler esastır. Alipay yalnızca tek seferlik alımlarda geçerlidir; abonelikler için kart, Apple Pay veya Google Pay gerekir. Tüm fiyatlar USD cinsindendir, yerel para birimine çevrim ödeme sırasında otomatik yapılır.",
    "faq.q8": "Hangi görsel formatları destekleniyor?",
    "faq.a8": "20 MB'a kadar JPG, PNG ve WebP kabul ediyoruz. Yapay zekâ, net çekilmiş gündüz mimari veya peyzaj fotoğraflarında en iyi sonucu verir.",

    // -- Blog page --
    "blog.heading": "Blog",
    "blog.subtitle": "Aydınlatma görselleştirmesi, yapay zekâ ile render iş akışları ve gece planlaması üzerine uygulamalı rehberler.",
    "blog.empty": "Henüz yayımlanmış yazı yok. Yakında tekrar uğrayın.",
    "blog.backToBlog": "← Blog'a dön",

    // -- Use Cases index --
    "useCases.heading": "Tasarımcılar LDR'yi nasıl kullanıyor",
    "useCases.subtitle": "Dört ayrı disiplin, tek bir ortak sorun: müşteriler tek bir armatür takılmadan önce gece aydınlatmasını görmek istiyor. LDR bu boşluğu her biri için kapatıyor.",
    "useCases.learnMore": "Daha fazlası →",
    "useCases.arch.title": "Mimari Aydınlatma",
    "useCases.arch.desc": "Cephe aydınlatmasını, giriş saçaklarını ve tarihi yapı aydınlatmasını montajdan önce görselleştirin. Mimarlar, aydınlatma danışmanları ve tasarla-yap müteahhitleri için.",
    "useCases.arch.keywords": "Cepheler · Girişler · Tarihi yapılar",
    "useCases.landscape.title": "Peyzaj Aydınlatması",
    "useCases.landscape.desc": "Bahçelerde yukarı aydınlatmayı, yürüyüş yolu aydınlatmasını ve su öğelerinin aydınlatmasını önceden görün. Peyzaj mimarları ve konut projesi tasarımcıları için.",
    "useCases.landscape.keywords": "Bahçeler · Yürüyüş yolları · Su öğeleri",
    "useCases.urban.title": "Kentsel Gece Planlaması",
    "useCases.urban.desc": "Kent ölçeğinde gece çevrelerini, köprü aydınlatmasını ve kamusal alan aydınlatmasını modelleyin. Şehir plancıları, kamu yapıları tasarımcıları ve belediye danışmanları için.",
    "useCases.urban.keywords": "Köprüler · Kamusal alan · Kamu yapıları",
    "useCases.hospitality.title": "Konaklama Aydınlatması",
    "useCases.hospitality.desc": "Otel cephelerini, havuz teraslarını, çatı barlarını ve butik restoran atmosferini görselleştirin. Konaklama aydınlatma danışmanları ve marka ekipleri için.",
    "useCases.hospitality.keywords": "Oteller · Tatil köyleri · Restoranlar · Barlar",
    "useCases.exploreOther": "Diğer Kullanım Alanları",

    // -- Meta (page titles / descriptions) --
    "meta.home.title": "Yapay Zekâ Aydınlatma Görselleştirme — Gündüzden Geceye",
    "meta.home.desc": "Gündüz fotoğraflarını yapay zekâ ile profesyonel gece görsellerine dönüştürün. Fotoğrafı yükleyin, aydınlatma fikrinizi anlatın, sonucu anında alın.",
    "meta.pricing.title": "Fiyatlandırma — LDR Aydınlatma Görselleştirme",
    "meta.pricing.desc": "Yapay zekâ ile gece render'da şeffaf fiyatlar. Günde 1 görselle ücretsiz başlayın, 9 dolardan paket alın ya da filigransız 4K için aylık 99 dolardan abone olun.",
    "meta.blog.title": "Blog — Aydınlatma Tasarımı ve Yapay Zekâ Render Rehberleri",
    "meta.blog.desc": "Yapay zekâ destekli aydınlatma render'ı, gece görselleştirme ve gündüzden geceye dönüşüm üzerine uygulamalı rehberler, dersler ve ipuçları.",
    "meta.useCases.title": "Kullanım Alanları — Aydınlatma Görselleştirme",
    "meta.useCases.desc": "Mimarların, aydınlatma tasarımcılarının ve şehir plancılarının mimari, peyzaj, kentsel ve konaklama projelerinde LDR ile nasıl çalıştığını görün.",
  },
} as const;
